// Кеңейтілген интерактивті модульдер: ортақ ойын күйі, XP және localStorage.
const gameQuestions = [
 ['«Көксерек» әңгімесінің авторы кім?', ['Мұхтар Әуезов','Сәбит Мұқанов','Шерхан Мұртаза','Оралхан Бөкей'],0,'«Көксерек» — Мұхтар Әуезовтің адам мен табиғат байланысын суреттеген әңгімесі.'],
 ['Құрмаш Көксерекке қандай қарым-қатынас жасайды?', ['Оны асырайды','Одан қашады','Оны сатады','Оны қуып жібереді'],0,'Құрмаш бөлтірікті асырап, бауыр басады.'],
 ['«Ақбілек» шығармасының басты кейіпкері кім?', ['Ақбілек','Баян','Қозы','Аян'],0,'Шығарма атауы басты кейіпкердің есімімен аталған.'],
 ['«Ер Төстік» қай жанрға жатады?', ['Ертегі','Роман','Повесть','Поэма'],0,'Ер Төстік — қазақтың қиял-ғажайып ертегісі.'],
 ['«Жусан иісі» шығармасының авторы кім?', ['Сайын Мұратбеков','Мұхтар Әуезов','Ғабит Мүсірепов','Бауыржан Момышұлы'],0,'«Жусан иісі» — Сайын Мұратбековтің әңгімесі.'],
 ['«Қан мен тер» трилогиясының авторы кім?', ['Әбдіжәміл Нұрпейісов','Ілияс Есенберлин','Мұхтар Мағауин','Ғабит Мүсірепов'],0,'Трилогияны Әбдіжәміл Нұрпейісов жазған.'],
 ['«Қызыл жебедегі» тарихи тұлға кім?', ['Тұрар Рысқұлов','Абай Құнанбайұлы','Шоқан Уәлиханов','Ыбырай Алтынсарин'],0,'Роман Тұрар Рысқұловтың өмір жолын арқау етеді.'],
 ['Қозы мен Баян қандай жырдың кейіпкерлері?', ['Ғашықтық жырының','Батырлық жырының','Мысалдың','Ертегінің'],0,'Бұл — қазақтың ғашықтық эпосы.'],
 ['«Балалық шаққа саяхат» кімнің шығармасы?', ['Бердібек Соқпақбаев','Оралхан Бөкей','Шерхан Мұртаза','Сәбит Мұқанов'],0,'Шығармада жазушының балалық шағы баяндалады.'],
 ['«Көксерек» атауы нені білдіреді?', ['Қасқырдың атын','Ауыл атауын','Адам есімін','Тау атауын'],0,'Көксерек — әңгіменің негізгі қасқыр кейіпкері.']
];
let activeGame = {type:'quiz', index:0, score:0, answered:false, timer:null, earned:0};
function award(amount){xp+=amount;persist();toast('+'+amount+' XP қосылды!')}
function levelData(){if(xp>=1000)return [5,'Әдебиет сарапшысы',100];if(xp>=600)return [4,'Білгір',((xp-600)/400)*100];if(xp>=300)return [3,'Зерттеуші',((xp-300)/300)*100];if(xp>=100)return [2,'Ізденуші',((xp-100)/200)*100];return [1,'Оқырман',xp]}
function library(){app.innerHTML=`<section class="map-hero"><div class="eyebrow">Сандық кітапхана</div><h1 class="display" style="font-size:52px;margin:8px 0">Шығармалар</h1><p class="lead">13 туынды, кейіпкерлер және ойлануға шақыратын әлемдер.</p></section><div class="cards">${works.map(card).join('')}</div>`}
function achievements(){let data=[['🎖️','Алғашқы қадам','Алғашқы ойынды аяқта',gamesDone>=1],['📖','Оқырман','3 шығарманы зертте',completed>=3],['🔥','Марафоншы','5 ойынды аяқта',gamesDone>=5],['🧠','Әдеби білгір','Тесттен 90% ал',scores.some(s=>s>=90)],['🐺','Көксерек зерттеушісі','Көксерек тапсырмасын аяқта',completed>=1],['📚','Кітапқұмар','10 шығарманы зертте',completed>=10],['🏆','Әдебиет сарапшысы','Барлық шығарманы аяқта',completed>=13]];app.innerHTML=`<section class="map-hero"><div class="eyebrow">Сенің белестерің</div><h1 class="display" style="font-size:52px;margin:8px 0">Жетістіктер</h1><p class="lead">Әр орындалған қадам жаңа белгі ашады.</p></section><div class="achievements">${data.map(x=>`<article class="work-card achievement ${x[3]?'':'locked'}"><span class="badge">${x[0]}</span><div><b>${x[1]}</b><p class="muted">${x[2]}</p><small>${x[3]?'Ашылды ✓':'Әлі жабық 🔒'}</small></div></article>`).join('')}</div>`}
function enhancedRoute(){let h=location.hash.slice(1);if(!h||h==='home')homeNew();else if(h==='library')library();else if(h==='achievements')achievements();else if(h==='characters')characters();else if(h==='profile')profileNew();else if(h==='daily')daily()}
window.addEventListener('hashchange',enhancedRoute);enhancedRoute();
function homeNew(){let u=typeof currentUser==='function'?currentUser():null,l=levelData();if(!u||!u.loggedIn)return;app.innerHTML=`<section class="hero"><div><div class="eyebrow">Жеке әдеби жолыңыз</div><h1>Қош келдіңіз,<br><em>${u.name}!</em></h1><p class="lead">Әдеби саяхатыңызды жалғастырыңыз. Бүгін жаңа шығарма, жаңа ой және жаңа белес күтіп тұр.</p><div class="actions"><button class="primary" data-go="map">Жалғастыру →</button><button class="secondary" data-go="daily">Бүгінгі тапсырма</button></div><div class="progress-box"><div class="progress-row"><span>${l[0]}-деңгей · ${l[1]}</span><b>${xp} XP</b></div><div class="track"><div class="fill" style="width:${Math.min(100,l[2])}%"></div></div></div></div><div class="hero-art"><div class="moon"></div><div class="book"></div><span class="star">✦</span><span class="star">✧</span><span class="star">✦</span></div></section><section class="section"><div class="section-head"><div><h2>Әдеби саяхатыңыз</h2><p>${completed} / 13 шығарма зерттелді · ${gamesDone} ойын аяқталды</p></div><button class="link" data-go="profile">Профиль →</button></div><div class="cards">${card(works[4])}${card(works[2])}${card(works[6])}</div></section>`}
function characters(){let people=works.slice(2,10).flatMap(w=>w.chars.split(', ').map((n,i)=>({n,w,i}))).filter(x=>x.n.length>2);app.innerHTML=`<section class="map-hero"><div class="eyebrow">Кейіпкерлер байланысы</div><h1 class="display" style="font-size:52px;margin:8px 0">Кейіпкерлер әлемі</h1></section><div class="cards">${people.map(p=>`<article class="work-card"><span class="tag">${p.w.title}</span><h3>${p.n}</h3><p class="muted">Рөлі: ${p.i?'оқиға желісіндегі кейіпкер':'негізгі кейіпкер'}</p><p class="muted">Қасиеттері мен әрекеттерін шығарма бетінен зертте.</p><button class="small-btn" onclick="openWork('${p.w.id}')">Шығарманы ашу</button></article>`).join('')}</div>`}
function profileNew(){let l=levelData(),avg=scores.length?Math.round(scores.reduce((a,b)=>a+b,0)/scores.length):0,u=typeof currentUser==='function'?currentUser():null,name=u?.name||'Оқырман',email=u?.email||'—';app.innerHTML=`<section class="profile-top"><div class="big-avatar">${name[0].toUpperCase()}</div><div><h1>Менің парақшам</h1><p class="muted">${name} · ${email}</p><p class="muted">${l[0]}-деңгей — ${l[1]} · 🔥 7 күн қатарынан</p></div></section><div class="stats"><article class="stat-card"><span class="muted">XP</span><strong>${xp}</strong><div class="track"><div class="fill" style="width:${Math.min(100,l[2])}%"></div></div></article><article class="stat-card"><span class="muted">Зерттелген</span><strong>${completed} / 13</strong><span class="muted">шығарма</span></article><article class="stat-card"><span class="muted">Аяқталған ойын</span><strong>${gamesDone}</strong><span class="muted">ойын</span></article><article class="stat-card"><span class="muted">Тест орташа</span><strong>${avg}%</strong><span class="muted">нәтиже</span></article></div><section class="section"><div class="section-head"><div><h2>Бүгінгі әдеби тапсырма</h2><p>Күн сайын бір рет +20 XP</p></div><button class="link" data-go="daily">Тапсырманы ашу →</button></div><div class="notice">Күнделікті тапсырма прогресті жылдамдатуға көмектеседі. Сыйлық бір рет қана беріледі.</div></section><div class="actions"><button class="secondary" onclick="editProfile()">Профильді өңдеу</button><button class="secondary" onclick="logoutUser()">Шығу</button></div>`}
window.editProfile=function(){let u=currentUser(),n=prompt('Аты-жөніңіз:',u.name);if(n&&n.trim()){u.name=n.trim();localStorage.setItem('adebiet-user',JSON.stringify(u));profileNew();toast('Профиль жаңартылды.')}}
function daily(){let key='adebiet-daily-'+new Date().toISOString().slice(0,10),claimed=localStorage.getItem(key);app.innerHTML=`<section class="game-panel"><div class="eyebrow">🌟 Бүгінгі әдеби тапсырма</div><h2>«Көксерек» шығармасының авторын ата.</h2><div class="options">${['Мұхтар Әуезов','Сайын Мұратбеков','Шерхан Мұртаза','Ғабит Мүсірепов'].map((x,i)=>`<button class="option" onclick="dailyAnswer(${i},'${key}')" ${claimed?'disabled':''}>${x}</button>`).join('')}</div><div id="dailyFeedback">${claimed?'<div class="result-line">Бүгінгі сыйлықты алдыңыз. Ертең қайта оралыңыз!</div>':''}</div></section>`}
window.dailyAnswer=function(i,key){let buttons=document.querySelectorAll('.option');buttons.forEach((b,n)=>{b.disabled=true;if(n===0)b.classList.add('correct');if(n===i&&i!==0)b.classList.add('wrong')});let claimed=localStorage.getItem(key);if(i===0&&!claimed){localStorage.setItem(key,'1');award(20);$('#dailyFeedback').innerHTML='<div class="result-line">Дұрыс жауап! Күнделікті +20 XP алынды.</div>'}else $('#dailyFeedback').innerHTML='<div class="result-line">Қате. Дұрыс жауап: Мұхтар Әуезов.</div>'}
window.games=function(){app.innerHTML=`<section class="map-hero"><div class="eyebrow">Ойнап үйрен</div><h1 class="display" style="font-size:52px;margin:8px 0">Ойын орталығы</h1><p class="lead">Барлық ойында жауап бірден тексеріліп, XP беріледі.</p></section><div class="game-grid">${[['♙','Кейіпкерді тап','10 сұрақтық әдеби блиц','quiz'],['↕','Оқиғаны ретте','Карталарды сүйреп ретте','sequence'],['⌘','Сөздік қазына','Сөз бен мағынаны сәйкестендір','match'],['⌁','Шығарманы тап','Белгілер арқылы шеш','guess'],['⚔','Әдеби дуэль','30 секундтық таймер','duel'],['✎','Жоғалған сөз','Сөйлемді толықтыр','quiz'],['❝','Үзіндіні таны','Шығармаға қатысты деректі тап','quiz'],['★','Әдеби марафон','Бес тапсырмалық сынақ','quiz']].map(g=>`<article class="game-card"><div class="game-icon">${g[0]}</div><h3>${g[1]}</h3><p class="muted">${g[2]}</p><button class="small-btn" style="background:var(--gold);color:#38293a" onclick="launchGame('${g[3]}')">Ойынды бастау</button></article>`).join('')}</div><div id="gameArea"></div>`}
window.launchGame=function(type){activeGame={type,index:0,score:0,answered:false,timer:null,earned:0};if(type==='sequence')return sequenceGame();if(type==='match')return matchGame();if(type==='guess')return guessGame();quizGame(type==='duel')}
function quizGame(timed=false){let q=gameQuestions[activeGame.index];$('#gameArea').innerHTML=`<section class="game-panel"><div class="quiz-status"><span>${timed?'⚔ Әдеби дуэль':'♙ Кейіпкерді тап'}</span><span id="timer">${timed?'00:30':''}</span><span>${activeGame.index+1} / ${gameQuestions.length}</span></div><div class="track"><div class="fill" style="width:${((activeGame.index)/gameQuestions.length)*100}%"></div></div><h2>${q[0]}</h2><div class="options">${q[1].map((a,i)=>`<button class="option" onclick="checkGameAnswer(${i})">${a}</button>`).join('')}</div><div id="feedback"></div></section>`;if(timed)startTimer()}
window.checkGameAnswer=function(i){if(activeGame.answered)return;activeGame.answered=true;clearInterval(activeGame.timer);let q=gameQuestions[activeGame.index], ok=i===q[2], buttons=document.querySelectorAll('.option');buttons.forEach((b,n)=>{b.disabled=true;if(n===q[2])b.classList.add('correct');if(n===i&&!ok)b.classList.add('wrong')});if(ok){activeGame.score++;activeGame.earned+=10;award(10)}$('#feedback').innerHTML=`<div class="result-line"><b>${ok?'Дұрыс жауап! ✓':'Қате жауап. ✕'}</b><br>${q[3]}<br><button class="primary" style="margin-top:12px" onclick="nextGameQuestion()">${activeGame.index===gameQuestions.length-1?'Нәтижені көру':'Келесі сұрақ →'}</button></div>`}
window.nextGameQuestion=function(){activeGame.index++;if(activeGame.index>=gameQuestions.length)return finishGame();activeGame.answered=false;quizGame(activeGame.type==='duel')}
function startTimer(){let n=30;activeGame.timer=setInterval(()=>{n--;let out=$('#timer');if(out)out.textContent='00:'+String(n).padStart(2,'0');if(n<=0){clearInterval(activeGame.timer);checkGameAnswer(-1)}},1000)}
function finishGame(){clearInterval(activeGame.timer);let pct=Math.round(activeGame.score/gameQuestions.length*100);gamesDone++;scores.push(pct);award(20+(pct===100?20:0));persist();$('#gameArea').innerHTML=`<section class="game-panel" style="text-align:center"><div class="game-icon">🎉</div><h2>Ойын аяқталды!</h2><h1>${activeGame.score} / ${gameQuestions.length}</h1><p>Дәлдік: <b>${pct}%</b> · Дұрыс: ${activeGame.score} · Қате: ${gameQuestions.length-activeGame.score}</p><p class="result-line">Алынған XP: +${activeGame.earned+20+(pct===100?20:0)}${pct>=90?' · 🧠 Әдеби білгір жетістігі ашылды!':''}</p><button class="primary" onclick="games()">Қайта ойнау</button><button class="secondary" data-go="map">Картаға оралу</button></section>`}
function sequenceGame(){let events=['Көксерек бөлтірік кезінде қолға түседі.','Құрмаш оны асырай бастайды.','Көксерек есейеді.','Көксерек табиғатқа қайта оралады.','Оқиға қайғылы жағдайға әкеледі.'];events.sort(()=>Math.random()-.5);$('#gameArea').innerHTML=`<section class="game-panel"><div class="eyebrow">Оқиғаны ретте</div><h2>Көксерек оқиғаларын дұрыс ретке орналастыр</h2><p class="muted">Карталарды сүйреп жылжытыңыз.</p><div id="dragList" class="drag-list">${events.map(x=>`<div draggable="true" class="drag-item">${x}</div>`).join('')}</div><button class="primary" style="margin-top:18px" onclick="checkSequence()">Тексеру</button><div id="seqResult"></div></section>`;enableDrag()}
function enableDrag(){let dragged;document.querySelectorAll('.drag-item').forEach(el=>{el.addEventListener('dragstart',()=>{dragged=el;el.classList.add('dragging')});el.addEventListener('dragend',()=>el.classList.remove('dragging'));el.addEventListener('dragover',e=>e.preventDefault());el.addEventListener('drop',e=>{e.preventDefault();if(dragged!==el){let p=el.parentNode,after=[...p.children].indexOf(dragged)<[...p.children].indexOf(el);p.insertBefore(dragged,after?el.nextSibling:el)}})})}
window.checkSequence=function(){let correct=['Көксерек бөлтірік кезінде қолға түседі.','Құрмаш оны асырай бастайды.','Көксерек есейеді.','Көксерек табиғатқа қайта оралады.','Оқиға қайғылы жағдайға әкеледі.'];let items=[...document.querySelectorAll('.drag-item')],n=0;items.forEach((x,i)=>{let ok=x.textContent===correct[i];x.classList.add(ok?'correct':'wrong');if(ok)n++});if(n===5){award(30);gamesDone++;persist()}$('#seqResult').innerHTML=`<div class="result-line">${n} / 5 дұрыс орналастырылды. ${n===5?'Тамаша! +30 XP':'Қайта орындап көріңіз.'}</div>`}
function matchGame(){let data=[['Кебеже','Азық-түлік сақтайтын ағаш сандық'],['Сауыт','Жауынгердің қорғаныс киімі'],['Жасау','Қызға берілетін дүние-мүлік'],['Шаңырақ','Киіз үйдің дөңгелек төбесі']];let defs=data.map(x=>x[1]).sort(()=>Math.random()-.5);$('#gameArea').innerHTML=`<section class="game-panel"><div class="eyebrow">Сөздік қазына</div><h2>Сөзді мағынасымен сәйкестендір</h2><div class="match-grid">${data.map((x,i)=>`<div><b>${x[0]}</b></div><select data-correct="${x[1]}"><option value="">Мағынасын таңдаңыз</option>${defs.map(d=>`<option>${d}</option>`).join('')}</select>`).join('')}</div><button class="primary" style="margin-top:18px" onclick="checkMatch()">Тексеру</button><div id="matchResult"></div></section>`}
window.checkMatch=function(){let inputs=[...document.querySelectorAll('.match-grid select')],n=0;inputs.forEach(x=>{let ok=x.value===x.dataset.correct;x.style.borderColor=ok?'#54a77d':'#dd7463';if(ok)n++});if(n===inputs.length){award(30);gamesDone++;persist()}$('#matchResult').innerHTML=`<div class="result-line">${n} / ${inputs.length} дұрыс. ${n===inputs.length?'Тамаша! +30 XP':'Қате жұптарды жасыл жауапқа қарап түзетіңіз.'}</div>`}
function guessGame(){let stage=1;function draw(){let clues=['Бұл шығармада адам мен табиғат арасындағы қарым-қатынас маңызды.','Негізгі образдардың бірі — қасқыр.','Автор — Мұхтар Әуезов.','Атауы сегіз әріптен тұрады.'];$('#gameArea').innerHTML=`<section class="game-panel"><div class="eyebrow">Шығарманы тап · ${stage}/4 белгі</div><h2>${clues[stage-1]}</h2><div class="options">${['Көксерек','Ұлпан','Ақбілек','Жусан иісі'].map(x=>`<button class="option" onclick="guessAnswer('${x}',${stage})">${x}</button>`).join('')}</div><div id="guessFeedback"></div></section>`}window.guessAnswer=(x,s)=>{let ok=x==='Көксерек';document.querySelectorAll('.option').forEach(b=>{b.disabled=true;if(b.textContent==='Көксерек')b.classList.add('correct');if(b.textContent===x&&!ok)b.classList.add('wrong')});if(ok){let v=[100,70,40,20][s-1];award(v);gamesDone++;persist();$('#guessFeedback').innerHTML=`<div class="result-line">Дұрыс! +${v} XP. Бұл — «Көксерек».</div>`}else if(s<4){$('#guessFeedback').innerHTML=`<div class="result-line">Қате. <button class="primary" onclick="nextGuess()">Келесі белгі</button></div>`}else $('#guessFeedback').innerHTML='<div class="result-line">Дұрыс жауап: Көксерек.</div>'};window.nextGuess=()=>{stage++;draw()};draw()}
