const difficultyById={alpan:'Орташа','kar-kyzy':'Орташа',kozy:'Оңай',zhabaiy:'Орташа',kokserak:'Орташа',ashkan:'Орташа',akbilek:'Қиын',ertostik:'Оңай',zhusan:'Оңай',balalyk:'Оңай',kan:'Қиын',aiqai:'Қиын',qyzyl:'Қиын'};
const works=Object.values(window.VERIFIED_LITERARY_DATA||{}).map(source=>({
 id:source.id,title:source.title,author:source.author,authorType:source.authorType,
 genre:source.genre,level:difficultyById[source.id]||'Орташа',desc:source.intro,
 chars:(source.content?.characters||[]).map(character=>character.name).join(', ')||'Дерек нақтылануда',
 themes:(source.content?.themes||[]).join(', ')||'Дерек нақтылануда',period:source.period,
 verificationStatus:source.verificationStatus
}));
function readLocalArray(key){try{const value=JSON.parse(localStorage.getItem(key)||'[]');return Array.isArray(value)?value:[]}catch{return []}}
let saved=readLocalArray('adebiet-favs'), xp=Number(localStorage.getItem('adebiet-xp'))||0, completed=Number(localStorage.getItem('adebiet-completed'))||0, gamesDone=Number(localStorage.getItem('adebiet-games'))||0, scores=readLocalArray('adebiet-scores');
const $=s=>document.querySelector(s); const app=$('#app');
function persist(){localStorage.setItem('adebiet-favs',JSON.stringify(saved));localStorage.setItem('adebiet-xp',xp);localStorage.setItem('adebiet-completed',completed);localStorage.setItem('adebiet-games',gamesDone);localStorage.setItem('adebiet-scores',JSON.stringify(scores))}
function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2300)}
function card(w){let f=saved.includes(w.id);return `<article class="work-card"><button class="heart ${f?'saved':''}" onclick="toggleFav('${w.id}')">${f?'♥':'♡'}</button><span class="tag">${w.genre}</span><h3>${w.title}</h3><div class="muted">${w.author}</div><p class="muted">${w.desc}</p><button class="small-btn" onclick="openWork('${w.id}')">Зерттеу →</button></article>`}
function home(){app.innerHTML=`<section class="hero"><div><div class="eyebrow">Қазақ әдебиетінің интерактивті әлемі</div><h1>ӘДЕБИ<br><em>САЯХАТ</em></h1><p class="lead">Кейіпкерлермен таныс. Оқиғаларды зертте. Біліміңді сына. Қазақ әдебиетін жаңа форматта аш.</p><div class="actions"><button class="primary" data-go="map">Саяхатты бастау</button><button class="secondary" data-go="map">Шығармаларды зерттеу</button></div><div class="progress-box"><div class="progress-row"><span>Сенің әдеби саяхатың</span><b>${Math.min(100,completed*8)}%</b></div><div class="track"><div class="fill" style="width:${Math.min(100,completed*8)}%"></div></div></div></div><div class="hero-art"><div class="moon"></div><div class="book"></div><span class="star">✦</span><span class="star">✧</span><span class="star">✦</span></div></section><section class="section"><div class="section-head"><div><h2>Бүгінгі шығарма</h2><p>Жылыту үшін бір әдемі қадам</p></div><button class="link" onclick="openWork('kokserak')">Толығырақ →</button></div><div class="cards">${card(works[4])}${card(works[2])}${card(works[6])}</div></section><section class="section"><div class="section-head"><div><h2>Жаңа тапсырмалар</h2><p>Күн сайын білімге бір қадам</p></div><button class="link" data-go="games">Барлық ойын →</button></div><div class="three-up"><article class="challenge"><span class="eyebrow">Бүгінгі әдеби тапсырма</span><h3>Көксеректің негізгі идеясын таны</h3><p class="muted">3 қысқа сұраққа жауап бер де, сыйлық ал.</p><button class="secondary" data-go="games">Тапсырманы бастау</button><p class="xp">+20 XP</p></article><article class="work-card achievement"><span class="badge">📚</span><div><b>Алғашқы қадам</b><p class="muted">Алғашқы шығарманы аяқта</p></div></article><article class="work-card achievement"><span class="badge">🔥</span><div><b>7 күн қатарынан</b><p class="muted">Сен үздіксіз ізденіп келесің</p></div></article></div></section>`}
function map(){app.innerHTML=`<section class="map-hero"><div class="eyebrow">13 әдеби мекен</div><h1 class="display" style="font-size:52px;margin:8px 0">Әдеби карта</h1><p class="lead">Әр шығарма — жаңа әлем. Өзіңе жол таңда.</p></section><div class="filterbar"><button class="filter active" onclick="filterMap('Барлығы',this)">Барлығы</button>${[...new Set(works.map(w=>w.genre))].map(g=>`<button class="filter" onclick="filterMap('${g}',this)">${g}</button>`).join('')}</div><div id="mapGrid" class="map-grid">${mapCards(works)}</div>`}
function mapCards(list){return list.map((w,i)=>`<button class="map-card" onclick="openWork('${w.id}')"><span class="map-num">${String(i+1).padStart(2,'0')} · ${w.genre}</span><h3>${w.title}</h3><span class="level">✦ ${w.level}</span></button>`).join('')}
function filterMap(g,el){document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));el.classList.add('active');$('#mapGrid').innerHTML=mapCards(g==='Барлығы'?works:works.filter(w=>w.genre===g))}
function openWork(id){let w=works.find(x=>x.id===id);location.hash='work/'+id;app.innerHTML=`<section class="detail-hero"><button class="back" data-go="map">← Әдеби картаға оралу</button><div class="eyebrow" style="margin-top:28px">${w.genre} · ${w.period}</div><h1>${w.title}</h1><div class="detail-meta">${w.author} шығармасы</div></section><section class="detail-grid"><div><article class="work-card" style="min-height:0;margin-bottom:17px"><h3>Спойлерсіз қысқаша</h3><p class="muted" style="font-size:15px">${w.desc} Бұл шығарма оқырманды кейіпкерлердің таңдауы мен ішкі әлемі туралы ойлануға шақырады.</p></article><div class="info-grid"><article class="info"><h3>Кейіпкерлер</h3><p class="muted">${w.chars}</p></article><article class="info"><h3>Тақырыптар</h3><p class="muted">${w.themes}</p></article><article class="info"><h3>Қызықты дерек</h3><p class="muted">Шығарманы дәуірі мен мәдени контексті арқылы оқып көріңіз.</p></article><article class="info"><h3>Дәйексөздер</h3><p class="muted">Нақты үзінділерді кітаптың түпнұсқасынан іздеңіз.</p></article></div></div><aside class="work-card detail-side"><span class="tag">Сенің жолың</span><h3>Шығарманы меңгеру</h3><div class="progress-row"><span>Зерттеу</span><b>35%</b></div><div class="track"><div class="fill" style="width:35%"></div></div><p class="muted">Тест тапсырып, осы мекенді игер.</p><button class="primary" onclick="games()">Тест тапсыру</button><button class="secondary" style="margin-top:9px" onclick="completeWork()">Аяқталды деп белгілеу</button></aside></section>`;window.scrollTo(0,0)}
function games(){app.innerHTML=`<section class="map-hero"><div class="eyebrow">Ойнап үйрен</div><h1 class="display" style="font-size:52px;margin:8px 0">Ойын орталығы</h1><p class="lead">Әдебиетке жақындай түсетін шағын сынақтар.</p></section><div class="game-grid">${[['♙','Кейіпкерді тап','Сипаттама арқылы кейіпкерді таны.'],['↕','Оқиғаны ретте','Оқиғаларды дұрыс ретке келтір.'],['❝','Дәйексөз кімге тиесілі?','Автор не кейіпкерді анықта.'],['⌁','Шығарманы тап','Белгілерге қарап шығарма таңда.'],['⚔','Әдеби дуэль','Таймермен жарысқа түс.'],['⌘','Сөздік қазына','Сөз бен мағынаны сәйкестендір.']].map((g,i)=>`<article class="game-card"><div class="game-icon">${g[0]}</div><h3>${g[1]}</h3><p class="muted">${g[2]}</p><button class="small-btn" style="background:var(--gold);color:#38293a" onclick="startQuiz(${i})">Ойынды бастау</button></article>`).join('')}</div><div id="gameArea"></div>`}
const questions=[{q:'«Көксерек» әңгімесінің авторы кім?',a:['Мұхтар Әуезов','Сәбит Мұқанов','Шерхан Мұртаза','Оралхан Бөкей'],c:0},{q:'Қозы мен Баян қандай эпостың кейіпкерлері?',a:['Батырлық жырының','Ғашықтық жырының','Ертегінің','Мысалдың'],c:1},{q:'«Ақбілек» шығармасының жанры?',a:['Поэма','Роман','Ертегі','Әңгіме'],c:1}];let qi=0,score=0;
function startQuiz(){qi=0;score=0;renderQ();document.querySelector('#gameArea').scrollIntoView({behavior:'smooth'})}function renderQ(){let q=questions[qi];$('#gameArea').innerHTML=`<section class="game-panel"><div class="quiz-status"><span>Әдеби блиц</span><span>${qi+1} / ${questions.length}</span></div><h2>${q.q}</h2><div class="options">${q.a.map((a,i)=>`<button class="option" onclick="answer(${i})">${a}</button>`).join('')}</div></section>`}function answer(i){let q=questions[qi],opts=document.querySelectorAll('.option');opts.forEach((x,n)=>{x.disabled=true;if(n===q.c)x.classList.add('correct');if(n===i&&i!==q.c)x.classList.add('wrong')});if(i===q.c){score++;xp+=10;persist();toast('+10 XP!')}setTimeout(()=>{qi++;if(qi<questions.length)renderQ();else finishQuiz()},750)}function finishQuiz(){$('#gameArea').innerHTML=`<section class="game-panel" style="text-align:center"><div class="game-icon">${score>1?'🏆':'📖'}</div><h2>${score}/${questions.length} дұрыс жауап</h2><p class="muted">Тамаша! Әрбір жауап — әдеби әлемге жаңа қадам.</p><button class="primary" onclick="games()">Тағы ойнау</button></section>`}
function assistant(){app.innerHTML=`<section class="map-hero"><div class="eyebrow">Әрқашан жаныңда</div><h1 class="display" style="font-size:52px;margin:8px 0">Әдеби көмекші ✦</h1><p class="lead">Күрделі ойды бірге тарқатайық. Мен нақты мәтін мен жалпы түсіндіруді ажыратып айтамын.</p></section><section class="assistant-layout"><aside class="assistant-card"><h3>Жылдам көмек</h3>${['Көксеректің идеясын түсіндір','Маған тест жаса','Әдеби терминді түсіндір','Емтиханға дайындалайық'].map(x=>`<button class="quick" onclick="quickChat('${x}')">${x} →</button>`).join('')}</aside><div class="chat"><div class="chat-head">✦ Әдеби көмекші <span class="muted">· қазақша</span></div><div class="messages" id="messages"><div class="bubble bot">Сәлем! Қай шығарма немесе кейіпкер туралы білгің келеді? Нақты дерек пен интерпретацияны бөлек көрсетемін.</div></div><form class="chat-form" onsubmit="sendChat(event)"><input id="chatInput" placeholder="Сұрағыңды жазыңыз..." /><button>Жіберу</button></form></div></section>`}
function quickChat(t){$('#chatInput').value=t;sendChat({preventDefault(){}})}function sendChat(e){e.preventDefault();let inp=$('#chatInput'),t=inp.value.trim();if(!t)return;$('#messages').insertAdjacentHTML('beforeend',`<div class="bubble user">${t}</div>`);inp.value='';setTimeout(()=>{$('#messages').insertAdjacentHTML('beforeend',`<div class="bubble bot"><b>Түсіндіру:</b> Бұл сұраққа шығармадағы негізгі тақырыптар мен кейіпкерлер әрекеті арқылы жауап беруге болады. «Көксерек» туралы айтсақ, онда адам мен табиғат арасындағы жауапкершілік мәселесі айқын көрінеді.<br><br><span class="muted">Ескерту: бұл — жалпы әдеби талдау; нақты дәйексөз келтірілмеді.</span></div>`);$('#messages').scrollTop=9999},450)}
function profile(){let badges=[['📚','Алғашқы қадам','Бір шығарманы аяқта',completed>0],['🎯','Тапқыр оқырман','Тесттен 90% ал',score===3],['🔥','Әдеби марафоншы','5 шығарманы зертте',completed>=5],['🏆','Әдеби білгір','10 шығарманы аяқта',completed>=10],['🧠','Кейіпкертанушы','50 кейіпкерді тап',false],['⭐','Зерттеуші','Картаны толық аяқта',completed>=13]];app.innerHTML=`<section class="profile-top"><div class="big-avatar">А</div><div><h1>Менің парақшам</h1><p class="muted">Ізденуші · 🔥 7 күн қатарынан</p></div></section><div class="stats"><article class="stat-card"><span class="muted">Деңгей</span><strong>2</strong><span class="muted">Ізденуші</span></article><article class="stat-card"><span class="muted">XP</span><strong>${xp}</strong><span class="muted">келесі деңгейге 80 XP</span></article><article class="stat-card"><span class="muted">Аяқталған</span><strong>${completed}</strong><span class="muted">шығарма</span></article><article class="stat-card"><span class="muted">Таңдаулы</span><strong>${saved.length}</strong><span class="muted">шығарма</span></article></div><section class="section"><div class="section-head"><div><h2>Менің жетістіктерім</h2><p>Жолыңдағы маңызды белестер</p></div></div><div class="achievements">${badges.map(b=>`<article class="work-card achievement ${b[3]?'':'locked'}"><span class="badge">${b[0]}</span><div><b>${b[1]}</b><p class="muted">${b[2]}</p></div></article>`).join('')}</div></section><section class="section"><div class="section-head"><div><h2>Таңдаулыларым</h2></div></div><div class="cards">${saved.length?saved.map(id=>card(works.find(w=>w.id===id))).join(''):'<div class="empty">Әлі таңдаулы шығарма жоқ. Картаны аралап көр!</div>'}</div></section>`}
function toggleFav(id){saved.includes(id)?saved=saved.filter(x=>x!==id):saved.push(id);persist();toast(saved.includes(id)?'Таңдаулыларға қосылды':'Таңдаулылардан алынды');let cur=location.hash;if(cur.startsWith('#work/'))openWork(id);else route()}
function completeWork(){completed=Math.min(13,completed+1);xp+=30;persist();toast('+30 XP · Шығарма игерілді!');openWork(location.hash.split('/')[1])}
function search(){$('#modalRoot').innerHTML=`<div class="modal-overlay" onclick="if(event.target===this)closeModal()"><div class="modal"><div class="modal-head"><h2>Іздеу</h2><button onclick="closeModal()">✕</button></div><input autofocus class="search-input" id="searchInput" placeholder="Шығарма, автор, кейіпкер..." oninput="doSearch()"><div id="results" class="empty">Іздеу сөзін енгізіңіз</div></div></div>`;$('#searchInput').focus()}
function doSearch(){let q=$('#searchInput').value.toLowerCase();let r=works.filter(w=>(w.title+w.author+w.chars).toLowerCase().includes(q));$('#results').innerHTML=q?(r.length?r.map(w=>`<button class="search-result" onclick="closeModal();openWork('${w.id}')"><span><b>${w.title}</b><br><small class="muted">${w.author} · ${w.genre}</small></span><span>→</span></button>`).join(''):'<div class="empty">Нәтиже табылмады</div>'):'<div class="empty">Іздеу сөзін енгізіңіз</div>'}
function closeModal(){$('#modalRoot').innerHTML=''}function route(){let hash=location.hash.slice(1);if(hash.startsWith('work/'))return openWork(hash.split('/')[1]);({map,games,assistant,profile}[hash]||home)();document.querySelectorAll('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.go===(hash||'home')));window.scrollTo(0,0)}document.addEventListener('click',e=>{let b=e.target.closest('[data-go]');if(b){location.hash=b.dataset.go}if(e.target.id==='searchBtn')search()});window.addEventListener('hashchange',route);route();
