(function(){
  'use strict';
  const BG='assets/games/asyk/backgrounds/',PC='assets/games/asyk/pieces/';
  const ASSETS=[BG+'asyk-village-intro.png',BG+'asyk-field-empty.png',BG+'asyk-field-start.png',PC+'asyk-piece-ivory-01.png',PC+'asyk-piece-ivory-02.png',PC+'asyk-piece-ivory-03.png',PC+'asyk-piece-gold.png',PC+'asyk-saka.png'];
  const ivory=[PC+'asyk-piece-ivory-01.png',PC+'asyk-piece-ivory-02.png',PC+'asyk-piece-ivory-03.png'];
  let S=null,raf=0,last=0,drag=null,audio=null,originalRender=null;
  const app=()=>document.querySelector('#app'),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const work=id=>(window.VERIFIED_LITERARY_DATA||{})[id]||null;
  function stop(){cancelAnimationFrame(raf);raf=0;document.body.classList.remove('asyk-playing');S=null}
  function render(workId='mix'){stop();S={workId,mode:null,state:'mode-selection',score:0,best:+localStorage.getItem('asyk-best')||0,correct:0,answered:0,gold:0,round:1,sound:true,pieces:[],assist:1,shots:0};app().innerHTML=`<section class="ax"><div class="ax-cover"><div class="ax-panel"><span class="ax-kicker">Ұлттық ойын · дәлдік</span><h1>Асық</h1><p>Сақаны тартып, бағытын таңда да, шеңбердегі асықтарды соғып шығар. Әр лақтыру — сенің шешімің.</p><div class="ax-modes"><button class="ax-mode" onclick="AsykGame.mode('literary')"><b>Әдеби режим</b><span>Лақтырулар арасында шығарма бойынша сұрақтар</span></button><button class="ax-mode" onclick="AsykGame.mode('free')"><b>Еркін ойын</b><span>Үзіліссіз раундтар және жиналатын ұпай</span></button></div><div class="ax-actions"><button class="ax-secondary" onclick="history.back()">← Ойындарға оралу</button></div></div></div></section>`;window.ShyrakAssistant?.say?.('Асыққа қош келдің! Режимді таңда, ережесін бірге меңгереміз.')}
  function mode(value){S.mode=value;S.state='ready';app().querySelector('.ax').innerHTML=`<div class="ax-cover"><div class="ax-panel"><img class="ax-ready-face" src="assets/shyrak/shyrak-talking.png" alt="Шырақ"><span class="ax-kicker">${value==='literary'?'Әдеби режим':'Еркін ойын'}</span><h1 style="font-size:clamp(38px,6vw,68px)">Дайынсың ба?</h1><p>${value==='literary'?'Дұрыс жауап сақаның күшін арттырады. Сұрақтан кейін ғана көзде.':'Сақаны өзің бағытта. Алты асықты шығарсаң, жаңа раунд басталады.'}</p><div id="axLoad" class="ax-loading">Ойын дайындалуда...</div><div class="ax-actions"><button id="axStart" class="ax-primary" disabled onclick="AsykGame.start()">Бастау</button><button class="ax-secondary" onclick="AsykGame.render('${S.workId}')">Режимді өзгерту</button></div></div></div>`;window.ShyrakAssistant?.say?.('Сақаны артқа тарт та, жібер. Бағыт пен күш өз қолыңда!');preload()}
  function preload(){Promise.all(ASSETS.map(src=>new Promise(r=>{const i=new Image;i.onload=i.onerror=r;i.src=src}))).then(()=>{const b=document.querySelector('#axStart'),l=document.querySelector('#axLoad');if(b)b.disabled=false;if(l){l.textContent='Ойын дайын';l.classList.add('ready')}})}
  function start(){S.state='scene-transition';document.body.classList.add('asyk-playing');app().innerHTML=`<section class="ax-stage"><div class="ax-field" id="axField"></div><div class="ax-cinematic"></div></section>`;setTimeout(()=>beginField(),matchMedia('(prefers-reduced-motion:reduce)').matches?350:1150)}
  function questions(){const w=S.workId==='mix'?null:work(S.workId);return window.NationalGames?.generateGameQuestions?.(w,'asyk','Қиын')||[]}
  function beginField(){if(!S)return;S.questions=questions();S.qIndex=0;const f=document.querySelector('#axField');if(!f)return;f.innerHTML=`<div class="ax-hud"><div class="ax-hud-group"><span class="ax-chip">Ұпай<b id="axScore">0</b></span><span class="ax-chip">Асық<b id="axLeft">6</b></span><span class="ax-chip">Раунд<b id="axRound">1</b></span></div><div class="ax-hud-group"><button class="ax-icon" id="axSound" onclick="AsykGame.sound()" aria-label="Дыбыс">🔊</button>${S.mode==='free'?'<button class="ax-secondary" onclick="AsykGame.finish()">Аяқтау</button>':''}</div></div><div class="ax-aim" id="axAim" hidden></div><div class="ax-hint" id="axHint">Сақаны артқа тартып, жібер</div><img class="ax-face" id="axFace" src="assets/shyrak/shyrak-idle.png" alt="Шырақ"><div class="ax-toast" id="axToast"></div>`;f.classList.add('live');spawn();bind();if(S.mode==='literary')showQuestion();else ready()}
  function spawn(){S.pieces=[];const pos=[[.42,.44],[.5,.41],[.58,.45],[.46,.52],[.55,.53],[.5,.48]];pos.forEach((p,i)=>S.pieces.push({id:i,type:i===5?'gold':'ivory',src:i===5?PC+'asyk-piece-gold.png':ivory[i%3],x:p[0],y:p[1],vx:0,vy:0,a:(i*47)%85-40,spin:0,m:i===5?1.12:1,out:false}));S.saka={id:'saka',type:'saka',src:PC+'asyk-saka.png',x:.5,y:.79,vx:0,vy:0,a:-8,spin:0,m:1.45,out:false};drawAll()}
  function drawAll(){const f=document.querySelector('#axField');if(!f)return;f.querySelectorAll('.ax-piece').forEach(x=>x.remove());[...S.pieces,S.saka].forEach(p=>{const el=document.createElement('img');el.src=p.src;el.alt=p.type==='gold'?'Алтын асық':p.type==='saka'?'Сақа':'Асық';el.className='ax-piece '+p.type;el.dataset.id=p.id;p.el=el;f.append(el)});paint();hud()}
  function paint(){[...S.pieces,S.saka].forEach(p=>{if(!p.el)return;p.el.style.left=(p.x*100)+'%';p.el.style.top=(p.y*100)+'%';p.el.style.setProperty('--r',p.a+'deg')})}
  function bind(){const f=document.querySelector('#axField');f.addEventListener('pointerdown',down);f.addEventListener('pointermove',move);f.addEventListener('pointerup',up);f.addEventListener('pointercancel',up)}
  function point(e){const r=document.querySelector('#axField').getBoundingClientRect();return{x:(e.clientX-r.left)/r.width,y:(e.clientY-r.top)/r.height,w:r.width,h:r.height}}
  function down(e){if(S.state!=='aiming'||!e.target.classList.contains('saka'))return;e.preventDefault();e.target.setPointerCapture(e.pointerId);drag={start:point(e),now:point(e)};e.target.classList.add('dragging');document.querySelector('#axHint').style.opacity=.15}
  function move(e){if(!drag)return;drag.now=point(e);const dx=(drag.start.x-drag.now.x)*drag.now.w,dy=(drag.start.y-drag.now.y)*drag.now.h,len=Math.min(150,Math.hypot(dx,dy));const a=document.querySelector('#axAim');a.hidden=false;a.style.left=(S.saka.x*100)+'%';a.style.top=(S.saka.y*100)+'%';a.style.width=len+'px';a.style.transform=`rotate(${Math.atan2(dy,dx)}rad)`}
  function up(e){if(!drag)return;const p=point(e),dx=(drag.start.x-p.x),dy=(drag.start.y-p.y),power=Math.min(.23,Math.hypot(dx,dy));drag=null;S.saka.el.classList.remove('dragging');document.querySelector('#axAim').hidden=true;if(power<.025){document.querySelector('#axHint').style.opacity=1;return}S.saka.vx=dx*2.6*S.assist;S.saka.vy=dy*2.6*S.assist;S.saka.spin=(dx+dy)*950;S.state='shooting';S.shots++;tone(150,.08);last=performance.now();raf=requestAnimationFrame(tick)}
  function tick(t){if(!S)return;const dt=Math.min(.025,(t-last)/1000||.016);last=t;const all=[S.saka,...S.pieces.filter(p=>!p.out)];all.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.a+=p.spin*dt;p.vx*=Math.pow(.18,dt);p.vy*=Math.pow(.18,dt);p.spin*=Math.pow(.12,dt)});collide(all);knockouts();paint();const moving=all.some(p=>Math.hypot(p.vx,p.vy)>.012);if(moving){raf=requestAnimationFrame(tick)}else settle()}
  function collide(all){const f=document.querySelector('#axField'),r=f.getBoundingClientRect();for(let i=0;i<all.length;i++)for(let j=i+1;j<all.length;j++){const a=all[i],b=all[j],dx=(b.x-a.x)*r.width,dy=(b.y-a.y)*r.height,d=Math.hypot(dx,dy),min=Math.min(r.width,r.height)*((a.type==='saka'||b.type==='saka') ? .057 : .05);if(d&&d<min){const nx=dx/d,ny=dy/d,rel=(b.vx-a.vx)*nx*r.width+(b.vy-a.vy)*ny*r.height;if(rel<0){const imp=-(1.5)*rel/(1/a.m+1/b.m);a.vx-=imp*nx/a.m/r.width;a.vy-=imp*ny/a.m/r.height;b.vx+=imp*nx/b.m/r.width;b.vy+=imp*ny/b.m/r.height;a.spin-=imp*.08;b.spin+=imp*.08;tone(270,.035)}const push=(min-d)/2;a.x-=nx*push/r.width;a.y-=ny*push/r.height;b.x+=nx*push/r.width;b.y+=ny*push/r.height}}}
  function knockouts(){S.pieces.forEach(p=>{if(p.out)return;
    /* Matches the painted ring in asyk-field-empty: x 8–92%, y 35–67%. */
    const visualRing=Math.hypot((p.x-.50)/.415,(p.y-.51)/.16);
    if(visualRing>1){p.out=true;p.el.classList.add('out');const points=p.type==='gold'?300:100;S.score+=points;if(p.type==='gold'){S.gold++;toast('Алтын асық +300');tone(620,.16)}else{toast('+100');tone(440,.09)}document.querySelector('#axFace').src='assets/shyrak/shyrak-talking.png';setTimeout(()=>p.el?.remove(),520);hud()}})}
  function settle(){S.state='settling';S.saka.x=.5;S.saka.y=.79;S.saka.vx=S.saka.vy=S.saka.spin=0;paint();setTimeout(()=>{if(!S)return;const left=S.pieces.filter(p=>!p.out).length;if(!left)return roundDone();document.querySelector('#axFace').src='assets/shyrak/shyrak-idle.png';if(S.mode==='literary')showQuestion();else ready()},500)}
  function ready(){S.state='aiming';document.querySelector('#axHint').style.opacity=1;document.querySelector('#axHint').textContent=S.assist>1?'Күш бонусы қосылды · сақаны тарт':'Сақаны артқа тартып, жібер'}
  function showQuestion(){S.state='question';const list=S.questions.length?S.questions:[{prompt:'«Көксерек» повесінің авторы кім?',options:['Мұхтар Әуезов','Абай Құнанбайұлы','Ілияс Жансүгіров'],answer:0}];const q=list[S.qIndex%list.length];S.current=q;const f=document.querySelector('#axField');const box=document.createElement('div');box.className='ax-question';box.innerHTML=`<article class="ax-qcard"><small>ЛАҚТЫРУ АЛДЫНДА</small><h2>${esc(q.prompt)}</h2><div class="ax-options">${q.options.map((o,i)=>`<button onclick="AsykGame.answer(${i})">${esc(o)}</button>`).join('')}</div></article>`;f.append(box)}
  function answer(i){const ok=i===S.current.answer;S.answered++;S.correct+=ok?1:0;S.qIndex++;S.assist=ok?1.18:.82;document.querySelector('#axFace').src=ok?'assets/shyrak/shyrak-talking.png':'assets/shyrak/shyrak-thinking.png';toast(ok?'Дұрыс · күш бонусы':'Келесіде сәттілік');document.querySelector('.ax-question')?.remove();setTimeout(ready,240)}
  function roundDone(){S.state='round-complete';toast('Раунд аяқталды!');tone(760,.22);if(S.mode==='free'){S.round++;setTimeout(()=>{spawn();ready()},900)}else setTimeout(finish,700)}
  function hud(){const left=S.pieces.filter(p=>!p.out).length;const a=document.querySelector('#axScore'),b=document.querySelector('#axLeft'),c=document.querySelector('#axRound');if(a)a.textContent=S.score;if(b)b.textContent=left;if(c)c.textContent=S.round}
  function toast(text){const e=document.querySelector('#axToast');if(!e)return;e.textContent=text;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),800)}
  function tone(freq,dur){if(!S.sound)return;try{audio=audio||new(window.AudioContext||window.webkitAudioContext)();const o=audio.createOscillator(),g=audio.createGain();o.frequency.value=freq;g.gain.setValueAtTime(.035,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+dur);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+dur)}catch{}}
  function sound(){S.sound=!S.sound;const b=document.querySelector('#axSound');if(b)b.textContent=S.sound?'🔊':'🔇'}
  function finish(){cancelAnimationFrame(raf);S.state='result';S.best=Math.max(S.best,S.score);localStorage.setItem('asyk-best',S.best);if(!S.saved){try{const rows=JSON.parse(localStorage.getItem('adebiet-game-results')||'[]'),total=S.mode==='literary'?S.answered:S.shots,correct=S.mode==='literary'?S.correct:S.pieces.filter(p=>p.out).length;rows.unshift({workId:S.workId,gameId:'asyk',score:S.score,total,correct,percent:total?Math.round(correct/total*100):0,date:new Date().toISOString(),mode:S.mode});localStorage.setItem('adebiet-game-results',JSON.stringify(rows.slice(0,100)));S.saved=true}catch{}}document.body.classList.remove('asyk-playing');app().innerHTML=`<section class="ax"><div class="ax-cover"><div class="ax-panel ax-result"><span class="ax-kicker">Ойын аяқталды</span><h1 style="font-size:clamp(38px,7vw,72px)">${S.score} ұпай</h1><dl><div><dt>Дұрыс жауап</dt><dd>${S.correct}/${S.answered}</dd></div><div><dt>Алтын асық</dt><dd>${S.gold}</dd></div><div><dt>Үздік нәтиже</dt><dd>${S.best}</dd></div></dl><div class="ax-actions" style="justify-content:center"><button class="ax-primary" onclick="AsykGame.render('${S.workId}')">Қайта ойнау</button><button class="ax-secondary" onclick="location.hash='games'">Ойындарға оралу</button></div></div></div></section>`}
  window.AsykGame={render,mode,start,answer,sound,finish,stop};
  function hook(){if(!window.NationalGames)return setTimeout(hook,0);originalRender=window.NationalGames.renderGame.bind(window.NationalGames);window.NationalGames.renderGame=(workId,gameId)=>gameId==='asyk'?render(workId):originalRender(workId,gameId)}hook();
  window.addEventListener('hashchange',()=>{if(!location.hash.includes('/asyk'))stop()});
})();
