// Прототиптік аутентификация: деректер тек осы браузердің localStorage-ында сақталады.
const AUTH_KEY='adebiet-user';
function currentUser(){try{return JSON.parse(localStorage.getItem(AUTH_KEY)||'null')}catch{return null}}
function showAuth(mode='login'){
  document.querySelector('.topbar').style.display='none';document.querySelector('.bottom-nav').style.display='none';
  document.querySelector('#app').innerHTML=`<section class="auth-shell"><div class="auth-card"><aside class="auth-intro"><img class="auth-logo" src="assets/brand/adebi-sayahat-logo.png" alt="Әдеби саяхат логотипі"><div class="eyebrow" style="color:#b8ead9">Ұлттық цифрлық платформа</div><h1>ӘДЕБИ<br>САЯХАТ</h1><p>Қазақ әдебиетінің әлеміне саяхат жаса. Шығармаларды зертте, біліміңді тексер, өз жолыңды құр.</p></aside><section class="auth-form">${mode==='login'?loginForm():registerForm()}</section></div></section>`
}
function loginForm(){return `<h2>Қош келдіңіз</h2><p class="muted">Жеке парақшаңызға кіріңіз.</p><form onsubmit="loginUser(event)"><label>Электрондық пошта</label><input id="loginEmail" type="email" placeholder="example@email.com" required><label>Құпиясөз</label><input id="loginPass" type="password" placeholder="Құпиясөзді енгізіңіз" required><div id="authMessage" class="auth-message"></div><button class="primary" type="submit">Кіру</button></form><div class="auth-switch">Әлі тіркелмедіңіз бе? <button onclick="showAuth('register')">Тіркелу</button></div>`}
function registerForm(){return `<h2>Тіркелу</h2><p class="muted">Әдеби саяхатыңызды бастау үшін деректерді толтырыңыз.</p><form onsubmit="registerUser(event)"><label>Аты-жөніңіз</label><input id="regName" placeholder="Атыңызды енгізіңіз" required minlength="2"><label>Электрондық пошта</label><input id="regEmail" type="email" placeholder="example@email.com" required><label>Құпиясөз</label><input id="regPass" type="password" placeholder="Құпиясөзді енгізіңіз" required minlength="4"><label>Құпиясөзді қайталаңыз</label><input id="regPass2" type="password" placeholder="Құпиясөзді қайталаңыз" required><div id="authMessage" class="auth-message"></div><button class="primary" type="submit">Тіркелу</button></form><div class="auth-switch">Есептік жазба бар ма? <button onclick="showAuth('login')">Кіру</button></div>`}
function authError(text){let e=document.querySelector('#authMessage');if(e)e.textContent=text}
window.registerUser=function(e){e.preventDefault();let name=document.querySelector('#regName').value.trim(),email=document.querySelector('#regEmail').value.trim().toLowerCase(),pass=document.querySelector('#regPass').value,pass2=document.querySelector('#regPass2').value;if(pass!==pass2)return authError('Құпиясөздер сәйкес емес.');let user={name,email,password:pass,loggedIn:true,createdAt:new Date().toISOString()};localStorage.setItem(AUTH_KEY,JSON.stringify(user));enterApp('Тіркелу сәтті аяқталды! Әдеби саяхатыңыз басталды.')}
window.loginUser=function(e){e.preventDefault();let u=currentUser(),email=document.querySelector('#loginEmail').value.trim().toLowerCase(),pass=document.querySelector('#loginPass').value;if(!u||u.email!==email||u.password!==pass)return authError('Электрондық пошта немесе құпиясөз қате.');u.loggedIn=true;localStorage.setItem(AUTH_KEY,JSON.stringify(u));enterApp('Қайта оралғаныңызға қуаныштымыз!')}
function enterApp(message){document.querySelector('.topbar').style.display='flex';document.querySelector('.bottom-nav').style.display='flex';location.hash='home';route();if(typeof enhancedRoute==='function')enhancedRoute();toast(message)}
window.logoutUser=function(){let u=currentUser();if(u){u.loggedIn=false;localStorage.setItem(AUTH_KEY,JSON.stringify(u))}location.hash='';showAuth('login')}
// Бастапқы қолжетімділік тек авторизацияланған пайдаланушыға беріледі.
window.addEventListener('DOMContentLoaded',()=>{let u=currentUser();if(!u||!u.loggedIn)showAuth('login')});
