// Әр ойын түріне жеке тапсырма банкі берілген; бір карточка басқа ойынның questions[0] мәніне қайта түспейді.
const DEDICATED_GAMES=Object.freeze({
  quote:{title:'Үзіндіні таны',items:[['Мазмұны бойынша: адам мен табиғат арасындағы қатынас өзек болатын шығарма қайсы?', ['Көксерек','Ұлпан','Ақбілек','Қан мен тер'],0,'Бұл — «Көксерек» туралы мазмұндық белгі; дәйексөз емес.'],['Мазмұны бойынша: Қозы мен Баянның махаббатын баяндайтын туындыны ата.', ['Қозы Көрпеш – Баян сұлу','Ер Төстік','Ұшқан ұя','Қар қызы'],0,'Бұл — қазақтың лиро-эпостық жыры.']]},
  missing:{title:'Жоғалған сөз',items:[['Мазмұндық тіркес: Құрмаш бөлтірікке ... деп ат қояды.', ['Көксерек','Ақбілек','Қозы','Аян'],0,'Құрмаш асыраған бөлтірікті Көксерек деп атайды.'],['«Ер Төстік» — қазақтың қиял-ғажайып ... .', ['ертегісі','романы','повесі','дастаны'],0,'Шығарма халық ертегісі жанрына жатады.']]},
  marathon:{title:'Әдеби марафон',items:[['«Қызыл жебе» шығармасының авторы кім?', ['Шерхан Мұртаза','Мұхтар Әуезов','Сайын Мұратбеков','Бауыржан Момышұлы'],0,'Автор — Шерхан Мұртаза.'],['«Қан мен тер» жанры қалай беріледі?', ['Роман-трилогия','Ертегі','Лиро-эпостық жыр','Повесть'],0,'«Қан мен тер» — роман-трилогия.'],['«Ұшқан ұя» авторы кім?', ['Бауыржан Момышұлы','Ғабит Мүсірепов','Оралхан Бөкей','Жүсіпбек Аймауытов'],0,'Автор — Бауыржан Момышұлы.']]}
});
window.games=function(){app.innerHTML=`<section class="map-hero"><div class="eyebrow">Ойын арқылы үйрен</div><h1 class="display" style="font-size:52px;margin:8px 0">Ойын орталығы</h1><p class="lead">Әр ойынның бөлек тапсырма реті, кері байланысы және XP есебі бар.</p></section><div class="game-grid">${[['♙','Кейіпкерді тап','quiz'],['↕','Оқиғаны ретте','sequence'],['⌘','Сөздік қазына','match'],['⌁','Шығарманы тап','guess'],['⚔','Әдеби дуэль','duel'],['✎','Жоғалған сөз','missing'],['❝','Үзіндіні таны','quote'],['★','Әдеби марафон','marathon']].map(g=>`<article class="game-card"><div class="game-icon">${g[0]}</div><h3>${g[1]}</h3><p class="muted">Мақсат, нәтиже және XP ойын аяқталғанда есептеледі.</p><button class="small-btn" style="background:var(--gold);color:white" onclick="launchGame('${g[2]}')">Ойынды бастау</button></article>`).join('')}</div><div id="gameArea"></div>`};
const oldLaunchGame=window.launchGame;
window.launchGame=function(type){if(!DEDICATED_GAMES[type])return oldLaunchGame(type);let game=DEDICATED_GAMES[type];window.dedicatedState={type,index:0,score:0,earned:0,game};renderDedicatedGame()};
function renderDedicatedGame(){let s=window.dedicatedState,q=s.game.items[s.index];document.querySelector('#gameArea').innerHTML=`<section class="game-panel"><div class="quiz-status"><span>${s.game.title}</span><span>${s.index+1} / ${s.game.items.length}</span></div><div class="track"><div class="fill" style="width:${s.index/s.game.items.length*100}%"></div></div><h2>${q[0]}</h2><div class="options">${q[1].map((x,i)=>`<button class="option" onclick="answerDedicated(${i})">${x}</button>`).join('')}</div><div id="dedicatedFeedback"></div></section>`}
window.answerDedicated=function(index){let s=window.dedicatedState,q=s.game.items[s.index],ok=index===q[2];document.querySelectorAll('.option').forEach((b,i)=>{b.disabled=true;if(i===q[2])b.classList.add('correct');if(i===index&&!ok)b.classList.add('wrong')});if(ok){s.score++;s.earned+=10;award(10)}document.querySelector('#dedicatedFeedback').innerHTML=`<div class="result-line"><b>${ok?'✓ Дұрыс жауап!':'✕ Қате жауап.'}</b><br>${q[3]}<br><button class="primary" style="margin-top:12px" onclick="nextDedicated()">${s.index===s.game.items.length-1?'Нәтижені көру':'Келесі сұрақ →'}</button></div>`};
window.nextDedicated=function(){let s=window.dedicatedState;s.index++;if(s.index<s.game.items.length)return renderDedicatedGame();gamesDone++;scores.push(Math.round(s.score/s.game.items.length*100));award(20);persist();document.querySelector('#gameArea').innerHTML=`<section class="game-panel" style="text-align:center"><h2>Ойын аяқталды!</h2><p>${s.score} / ${s.game.items.length} дұрыс жауап</p><p class="result-line">Алынған XP: +${s.earned+20}</p><button class="primary" onclick="games()">Ойындарға оралу</button></section>`};
