(function(){
  'use strict';
  const GAME_IDS=['asyk','langi','kokpar','arkan'];
  const META={
    asyk:{title:'Асық ату',subtitle:'Дәлдік пен білім',difficulty:'Орташа',desc:'Әдеби тапсырманы шешіп, дәл көздеп сақаны жібер.',accent:'#c96d3d'},
    langi:{title:'Ләңгі',subtitle:'Реакция мен есте сақтау',difficulty:'Жеңіл',desc:'Дәл сәтте соққы жасап, кейіпкерлер туралы деректі аш.',accent:'#337e76'},
    kokpar:{title:'Көкпар',subtitle:'Жылдамдық пен әдеби сайыс',difficulty:'Қиын',desc:'Жылдам жауап беріп, командаңды мәреге жеткіз.',accent:'#3e6f91'},
    arkan:{title:'Арқан тартыс',subtitle:'Логика мен талдау',difficulty:'Орташа',desc:'Дұрыс талдаумен арқанды өз жағыңа тарт.',accent:'#80594d'}
  };
  const root=()=>document.querySelector('#app');
  const allWorks=()=>Object.values(window.VERIFIED_LITERARY_DATA||{});
  const byId=id=>(window.VERIFIED_LITERARY_DATA||{})[id]||null;
  const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const userKey=()=>{try{return typeof currentUser==='function'?(currentUser()?.email||'guest'):'guest'}catch{return 'guest'}};
  const progressKey=()=>`adebiet-national-games::${userKey()}`;
  const readProgress=()=>{try{return JSON.parse(localStorage.getItem(progressKey())||'{}')}catch{return {}}};
  const writeProgress=value=>localStorage.setItem(progressKey(),JSON.stringify(value));
  const reduceMotion=()=>matchMedia('(prefers-reduced-motion: reduce)').matches;
  let session=null,raf=0,timers=[];
  const later=(fn,ms)=>{const id=setTimeout(fn,ms);timers.push(id);return id};
  function cleanup(){cancelAnimationFrame(raf);raf=0;timers.forEach(clearTimeout);timers=[];document.removeEventListener('keydown',keyHandler);document.body.classList.remove('ng-game-active')}
  function say(text){window.ShyrakAssistant?.say?.(text)}
  function syncNav(){document.querySelectorAll('[data-go]').forEach(b=>b.classList.toggle('active',b.dataset.go==='games'))}
  function richWorks(){return allWorks().filter(w=>w.content&&(w.content.characters?.length||w.content.themes?.length||w.content.plotEvents?.length))}
  function shuffle(rows){return [...rows].sort(()=>Math.random()-.5)}
  function unique(rows){return [...new Set(rows.filter(Boolean))]}
  function distract(correct,pool,count=3){return shuffle(unique(pool).filter(v=>v!==correct)).slice(0,count)}
  function question(prompt,correct,pool,explanation,type='knowledge'){
    const options=shuffle([correct,...distract(correct,pool)]);return {prompt,options,answer:options.indexOf(correct),explanation,type};
  }
  function generateGameQuestions(work,gameType,difficulty='Орташа'){
    const sourceWorks=work?[work]:richWorks(),globalCharacters=allWorks().flatMap(w=>w.content?.characters||[]).map(c=>c.name);
    const globalThemes=allWorks().flatMap(w=>w.content?.themes||[]).map(t=>typeof t==='string'?t:t.name);
    const rows=[];
    sourceWorks.forEach(w=>{
      const c=w.content||{},chars=c.characters||[],themes=(c.themes||[]).map(t=>typeof t==='string'?t:t.name);
      chars.forEach(ch=>rows.push(question(`«${w.title}» шығармасындағы «${ch.role||'кейіпкер'}» кім?`,ch.name,globalCharacters,`${ch.name}: ${ch.description||ch.role||'тексерілген кейіпкер'}.`,'character')));
      if(chars.length>1)chars.filter(ch=>ch.description).slice(0,3).forEach(ch=>rows.push(question(`Сипаттаманы таны: ${ch.description}`,ch.name,globalCharacters,`Бұл — ${ch.name}.`,'character')));
      themes.slice(0,3).forEach(theme=>rows.push(question(`«${w.title}» шығармасына тән тақырыпты таңда.`,theme,globalThemes,`Тексерілген тақырып: ${theme}.`,'theme')));
      (c.relationships||[]).slice(0,3).forEach(rel=>rows.push(question(`${rel.from}: «${rel.type}» байланысы қай кейіпкерге қатысты?`,rel.to,globalCharacters,`${rel.from} — ${rel.type} — ${rel.to}.`,'relationship')));
      (c.plotEvents||[]).slice(0,3).forEach(event=>rows.push(question(`«${w.title}» оқиғасын тап.`,event.text,allWorks().map(x=>x.content?.plotSummary).filter(Boolean),event.text,'event')));
      rows.push(question(`«${w.title}» шығармасының авторын таңда.`,w.author,allWorks().map(x=>x.author),`${w.title} — ${w.author} шығармасы.`,'author'));
      rows.push(question(`«${w.title}» жанрын таңда.`,w.genre,allWorks().map(x=>x.genre),`Жанры: ${w.genre}.`,'genre'));
    });
    const fallback=sourceWorks[0];
    if(rows.length<3&&fallback)rows.push(question(`«${fallback.title}» авторы кім?`,fallback.author,allWorks().map(x=>x.author),`${fallback.title} — ${fallback.author} шығармасы.`));
    const count={Жеңіл:4,Орташа:5,Қиын:7}[difficulty]||5;
    return shuffle(rows).slice(0,Math.min(count,rows.length));
  }
  function gameArt(id,large=false){
    if(id==='asyk')return `<div class="ng-art ng-art-asyk ${large?'large':''}" aria-hidden="true"><i class="sun"></i><i class="dune d1"></i><i class="dune d2"></i><span class="asyk a1"></span><span class="asyk a2"></span><span class="asyk a3"></span><span class="saka"></span><b class="ornament">⌁</b></div>`;
    if(id==='langi')return `<div class="ng-art ng-art-langi ${large?'large':''}" aria-hidden="true"><i class="wall"></i><i class="tree"></i><span class="langi-object"><u></u></span><i class="motion m1"></i><i class="motion m2"></i><b class="ornament">⌁</b></div>`;
    if(id==='kokpar')return `<div class="ng-art ng-art-kokpar ${large?'large':''}" aria-hidden="true"><i class="mountain m1"></i><i class="mountain m2"></i><i class="track"></i><span class="rider blue"><u></u><b></b></span><span class="rider gold"><u></u><b></b></span><i class="dust"></i></div>`;
    return `<div class="ng-art ng-art-arkan ${large?'large':''}" aria-hidden="true"><i class="tent"></i><span class="team left"><u></u><u></u><u></u></span><span class="rope"><b></b></span><span class="team right"><u></u><u></u><u></u></span><i class="ground"></i></div>`;
  }
  function stats(){const p=readProgress(),rows=Object.values(p);return {played:rows.reduce((n,r)=>n+(r.plays||0),0),gold:rows.filter(r=>r.medal==='Алтын').length,best:Math.max(0,...rows.map(r=>r.bestScore||0))}}
  function selector(selected){return `<label class="ng-select-wrap"><span>Шығарма</span><select id="ngWorkSelect" onchange="NationalGames.selectWork(this.value)"><option value="mix" ${selected==='mix'?'selected':''}>Еркін ойын · аралас шығармалар</option>${richWorks().map(w=>`<option value="${w.id}" ${selected===w.id?'selected':''}>${esc(w.title)}</option>`).join('')}</select></label>`}
  function card(id,workId){const m=META[id],p=readProgress()[`${workId}:${id}`]||{};return `<article class="ng-card ng-${id}" style="--accent:${m.accent}">${gameArt(id)}<div class="ng-card-body"><div class="ng-card-top"><span class="ng-difficulty">${m.difficulty}</span>${p.medal?`<span class="ng-medal mini">${p.medal}</span>`:''}</div><h2>${m.title}</h2><strong>${m.subtitle}</strong><p>${m.desc}</p><div class="ng-card-stats"><span>Үздік: <b>${p.bestScore||0}</b></span><span>${p.plays||0} рет</span></div><button class="ng-play" onclick="NationalGames.launch('${workId}','${id}')">Ойнау <span>→</span></button></div></article>`}
  const literaryKind=game=>game.type==='order'?'timeline':game.type==='match'?'matching':/кейіпкер|кім туралы/i.test(game.title)?'character':'quiz';
  function literaryArt(kind){return `<div class="ng-lit-art ${kind}" aria-hidden="true"><i></i><i></i><i></i><b></b></div>`}
  function literaryCard(work,game){const kind=literaryKind(game),labels={timeline:'Сюжетті ретте',matching:'Сәйкестендіру',character:'Кейіпкерді тап',quiz:'Тест / Викторина'};return `<article class="ng-literary-game"><div>${literaryArt(kind)}<span class="ng-difficulty">${esc(game.difficulty||'Орташа')}</span></div><section><small>Әдеби ойын · ${esc(work.title)}</small><h3>${labels[kind]||esc(game.title)}</h3><p>${esc(game.instruction||game.learningObjective)}</p><button class="ng-play" onclick="openGame('${work.id}','${game.id}')">Ойнау <span>→</span></button></section></article>`}
  function extraLiteraryCards(work){return `<article class="ng-literary-game"><div>${literaryArt('builder')}<span class="ng-difficulty">Логика</span></div><section><small>Әдеби ойын · ${esc(work.title)}</small><h3>Сюжетті жина</h3><p>Оқиға фрагменттерін біртұтас әдеби желіге жина.</p><button class="ng-play" onclick="NationalGames.openStoryBuilder('${work.id}')">Ойнау <span>→</span></button></section></article><article class="ng-literary-game"><div>${literaryArt('branch')}<span class="ng-difficulty">Шығармашылық</span></div><section><small>Әдеби ойын · ${esc(work.title)}</small><h3>Сюжетті өзгерту</h3><p>Шешім таңдап, оқиғаның балама бағытын зертте.</p><button class="ng-play" onclick="NationalGames.openStoryRewrite('${work.id}')">Ойнау <span>→</span></button></section></article>`}
  function literaryRows(selected,compact=false){let pairs=[];if(selected!=='mix'){const w=byId(selected);pairs=(w?.games||[]).map(g=>[w,g])}else allWorks().forEach(w=>(w.games||[]).forEach(g=>pairs.push([w,g])));const seen=new Set();pairs=pairs.filter(([,g])=>{const k=literaryKind(g);if(selected==='mix'&&seen.has(k))return false;seen.add(k);return true});const base=byId(selected==='mix'?'kokserak':selected)||byId('kokserak');return `${pairs.map(([w,g])=>literaryCard(w,g)).join('')}${base?extraLiteraryCards(base):''}`}
  function tabs(){return `<nav class="ng-tabs" aria-label="Ойын санаттары"><button class="active" onclick="NationalGames.filter('all',this)">Барлығы</button><button onclick="NationalGames.filter('literary',this)">Әдеби ойындар</button><button onclick="NationalGames.filter('national',this)">Ұлттық ойындар</button></nav>`}
  function filter(kind,button){document.querySelectorAll('.ng-tabs button').forEach(b=>b.classList.toggle('active',b===button));document.querySelectorAll('[data-game-section]').forEach(s=>s.hidden=kind!=='all'&&s.dataset.gameSection!==kind)}
  function renderHub(selected='mix'){
    cleanup();session=null;const s=stats();root().innerHTML=`<section class="ng-hub"><header class="ng-hero"><div><span class="ng-kicker">Әдеби білім · ұлттық мұра</span><h1>Ойындар <em>орталығы</em></h1><p>Әдеби тапсырмалар мен қазақтың ұлттық ойындары бір кеңістікте. Шығарманы таңда да, өзіңе ұнайтын механикамен білімді бекіт.</p><div class="ng-hero-stats"><span><b>${s.played}</b> ойын</span><span><b>${s.gold}</b> алтын</span><span><b>${s.best}</b> үздік ұпай</span></div></div><div class="ng-hero-scene"><i class="ng-moon"></i><i class="ng-steppe s1"></i><i class="ng-steppe s2"></i><span>Әдебиет пен ойын.<br>Бір саяхат.</span></div></header><div class="ng-toolbar">${selector(selected)}<div class="ng-mode"><b>${selected==='mix'?'Еркін ойын':'Шығарма режимі'}</b><span>Таңдауыңыз екі санаттағы тапсырмаларға да қолданылады.</span></div></div>${tabs()}<section class="ng-category" data-game-section="literary"><header><div><span>01 · Әдеби білім</span><h2>Әдеби ойындар</h2></div><p>Сюжет, кейіпкер және байланыстарды интерактивті механикалармен зертте.</p></header><div class="ng-literary-grid">${literaryRows(selected)}</div></section><section class="ng-category" data-game-section="national"><header><div><span>02 · Ұлттық мұра</span><h2>Ұлттық ойындар</h2></div><p>Дәлдік, реакция, жылдамдық және талдауды әдеби мазмұнмен ұштастыр.</p></header><div class="ng-grid">${GAME_IDS.map(id=>card(id,selected)).join('')}</div></section></section>`;syncNav();window.scrollTo(0,0)
  }
  function renderWorkHub(id){const work=byId(id);if(!work)return renderHub();cleanup();window.currentWorkId=id;root().innerHTML=`<section class="ng-hub ng-work-hub"><button class="back" data-go="games">← Ойындар орталығына</button><header class="ng-work-head"><div><span class="ng-kicker">${esc(work.author)}</span><h1>«${esc(work.title)}» <em>ойындары</em></h1><p>${esc(work.intro)}</p></div><aside><b>Екі ойын бағыты</b><span>Әдеби механикалар және төрт ұлттық ойын осы шығарманың деректерін қолданады.</span></aside></header>${tabs()}<section class="ng-category" data-game-section="literary"><header><div><span>01</span><h2>Әдеби ойындар</h2></div></header><div class="ng-literary-grid">${literaryRows(id)}</div></section><section class="ng-category" data-game-section="national"><header><div><span>02</span><h2>Ұлттық ойындар</h2></div></header><div class="ng-grid">${GAME_IDS.map(game=>card(game,id)).join('')}</div></section><button class="secondary" onclick="openWork('${id}')">Шығармаға оралу</button></section>`;syncNav();window.scrollTo(0,0)
  }
  function renderGame(workId,gameId){
    if(!GAME_IDS.includes(gameId))return;cleanup();document.body.classList.add('ng-game-active');const work=workId==='mix'?null:byId(workId);if(workId!=='mix'&&!work)return renderHub();
    const difficulty='Орташа';session={workId,work,gameId,difficulty,questions:generateGameQuestions(work,gameId,difficulty),stage:'start',round:0,score:0,correct:0,combo:0,bestCombo:0,attempts:0,position:0,player:0,opponent:0,started:0};
    root().innerHTML=`<section class="ng-game"><button class="back ng-back" onclick="NationalGames.exit()">← Ойындар орталығына</button><div id="ngShell"></div></section>`;renderStart();syncNav();window.scrollTo(0,0)
  }
  function workTitle(){return session.work?.title||'Еркін ойын'}
  function renderStart(){const m=META[session.gameId];document.querySelector('#ngShell').innerHTML=`<article class="ng-start ng-theme-${session.gameId}"><div class="ng-start-copy"><span class="ng-kicker">${esc(workTitle())}</span><h1>${m.title}</h1><h2>${m.subtitle}</h2><p>${m.desc} Әдеби тапсырмалар жобаның тексерілген деректерінен автоматты түрде құрылады.</p><div class="ng-difficulties" role="group" aria-label="Қиындық деңгейі">${['Жеңіл','Орташа','Қиын'].map(d=>`<button class="${d===session.difficulty?'active':''}" onclick="NationalGames.difficulty('${d}')">${d}</button>`).join('')}</div><button class="ng-start-btn" onclick="NationalGames.start()">Бастау <span>→</span></button></div>${gameArt(session.gameId,true)}<div class="ng-shyrak-note"><img src="assets/shyrak/shyrak-talking.png" alt="Шырақ"><span>Дайынсың ба? Бастайық!</span></div></article>`}
  function difficulty(value){session.difficulty=value;session.questions=generateGameQuestions(session.work,session.gameId,value);renderStart()}
  function start(){session.stage='play';session.started=performance.now();say('Дайынсың ба? Бастайық!');if(session.gameId==='asyk')renderAsykQuestion();if(session.gameId==='langi')renderLangi();if(session.gameId==='kokpar')renderRace();if(session.gameId==='arkan')renderArkan();document.addEventListener('keydown',keyHandler);window.scrollTo(0,0)}
  function header(label='Раунд'){const total=session.gameId==='langi'?10:session.questions.length;return `<header class="ng-gamebar"><div><span>${META[session.gameId].title}</span><b>${esc(workTitle())}</b></div><div class="ng-live-stats"><span>Ұпай <b>${session.score}</b></span><span>${label} <b>${Math.min(session.round+1,total)}/${total}</b></span><button class="ng-guide-mini" onclick="ShyrakAssistant.open()" aria-label="Шырақтан көмек сұрау"><img src="assets/shyrak/shyrak-talking.png" alt=""></button><button onclick="NationalGames.restart()" aria-label="Қайта бастау">↻</button></div></header>`}
  function qCard(q,handler){return `<section class="ng-literary-card"><span>Әдеби тапсырма</span><h2>${esc(q.prompt)}</h2><div class="ng-answers">${q.options.map((o,i)=>`<button onclick="${handler}(${i})">${esc(o)}</button>`).join('')}</div></section>`}
  function renderAsykQuestion(){if(session.round>=session.questions.length)return finish();const q=session.questions[session.round];document.querySelector('#ngShell').innerHTML=`${header()}<div class="ng-scene ng-asyk-scene"><div class="ng-sky"><i></i><b></b></div><div class="ng-field-wrap">${qCard(q,'NationalGames.asykAnswer')}<div class="ng-field-preview">Дұрыс жауап дәлдеу аймағын кеңейтеді.</div></div></div>`}
  function asykAnswer(index){const q=session.questions[session.round],ok=index===q.answer;session.correct+=ok?1:0;session.assist=ok;session.combo=ok?session.combo+1:0;session.bestCombo=Math.max(session.bestCombo,session.combo);say(ok?'Керемет! Енді дәл көзде.':'Асықпа, қолыңнан келеді. Енді сақамен байқап көр.');renderAsykField(q,ok)}
  function asykTargets(){return [{x:35,y:30,r:-14},{x:49,y:26,r:11},{x:62,y:34,r:-7},{x:43,y:41,r:22},{x:57,y:45,r:-20}].map((t,i)=>`<span class="ng-asyk-target" data-target style="--x:${t.x}%;--y:${t.y}%;--r:${t.r}deg"><b>${i+1}</b></span>`).join('')}
  function renderAsykField(q,ok){document.querySelector('#ngShell').innerHTML=`${header()}<div class="ng-scene ng-asyk-scene"><div class="ng-sky"><i></i><b></b></div><div class="ng-asyk-field" id="asykField"><div class="ng-field-pattern"></div>${asykTargets()}<div class="ng-aim ${ok?'assisted':''}" id="aimLine"></div><button class="ng-saka" id="saka" aria-label="Сақаны тартып, жіберіңіз"><i></i></button><div class="ng-power"><span>Күш</span><i id="powerFill"></i></div><div class="ng-field-tip">Сақаны төменге тартып, нысанаға қарай жібер</div></div><div class="ng-round-note"><b>${ok?'Дәлдеу көмегі қосылды':'Қалыпты дәлдеу'}</b><span>${esc(q.explanation)}</span></div></div>`;bindAsyk()}
  function bindAsyk(){const field=document.querySelector('#asykField'),saka=document.querySelector('#saka');let start=null,drag=null;
    saka.addEventListener('pointerdown',e=>{saka.setPointerCapture(e.pointerId);start={x:e.clientX,y:e.clientY};drag={x:0,y:0};saka.classList.add('dragging')});
    saka.addEventListener('pointermove',e=>{if(!start)return;drag={x:Math.max(-90,Math.min(90,e.clientX-start.x)),y:Math.max(0,Math.min(125,e.clientY-start.y))};const power=Math.min(100,Math.hypot(drag.x,drag.y)/1.25);document.querySelector('#powerFill').style.width=`${power}%`;document.querySelector('#aimLine').style.cssText+=`;--angle:${Math.atan2(drag.x,drag.y)*180/Math.PI}deg;--length:${Math.min(150,Math.hypot(drag.x,drag.y)*1.2)}px`});
    saka.addEventListener('pointerup',()=>{if(!start)return;const d=drag;start=null;saka.classList.remove('dragging');shootAsyk(field,saka,d)});
  }
  function shootAsyk(field,saka,drag){const strength=Math.hypot(drag.x,drag.y);if(strength<24){say('Сақаны сәл күштірек тарт.');return}const rect=field.getBoundingClientRect(),s=saka.getBoundingClientRect(),sx=s.left+s.width/2-rect.left,sy=s.top+s.height/2-rect.top,vx=-drag.x*3.15,vy=-drag.y*3.15;let best=null;
    field.querySelectorAll('[data-target]').forEach(el=>{const r=el.getBoundingClientRect(),tx=r.left+r.width/2-rect.left,ty=r.top+r.height/2-rect.top,t=Math.max(0,Math.min(1,((tx-sx)*vx+(ty-sy)*vy)/(vx*vx+vy*vy))),dist=Math.hypot(sx+vx*t-tx,sy+vy*t-ty);if(!best||dist<best.dist)best={el,dist}});
    const threshold=session.assist?54:37,hit=best&&best.dist<threshold;saka.style.transform=`translate(${vx}px,${vy}px) rotate(${(vx+vy)*.45}deg)`;field.classList.add('shot');later(()=>{if(hit){best.el.classList.add('hit');session.score+=100+Math.round(strength);session.combo++;say('Жарайсың! Дәл тиді!')}else{session.combo=0;say('Сәл мүлт кетті. Келесі лақтыруда дәлдей түс.')};session.bestCombo=Math.max(session.bestCombo,session.combo);session.round++;later(()=>session.round>=session.questions.length?finish():renderAsykQuestion(),720)},reduceMotion()?40:650)}
  function renderLangi(){document.querySelector('#ngShell').innerHTML=`${header('Соққы')}<div class="ng-scene ng-langi-scene" id="langiScene"><div class="ng-courtyard"><i class="ng-cloud c1"></i><i class="ng-cloud c2"></i><i class="ng-tree"></i><i class="ng-yurt"></i></div><div class="ng-langi-lane"><div class="ng-langi-item" id="langiItem"><i></i></div><div class="ng-hit-zone"><span>ДӘЛ СОҚҚЫ</span></div><div class="ng-tap-hint">Бос орын немесе экранды түрт</div><output id="langiFeedback"></output></div><aside class="ng-unlock"><span>Ашылған әдеби дерек</span><div id="langiFact">Серия жаса — дерек ашылады</div><b id="langiCombo">x1</b></aside></div>`;session.round=0;session.attempts=0;session.combo=0;session.langiStart=performance.now();document.querySelector('#langiScene').addEventListener('pointerdown',langiTap);langiLoop()}
  function langiLoop(now=performance.now()){if(!session||session.gameId!=='langi'||session.stage!=='play')return;const speed={Жеңіл:1700,Орташа:1400,Қиын:1100}[session.difficulty],p=Math.min(1,(now-session.langiStart)/speed);session.langiY=p;const item=document.querySelector('#langiItem');if(item)item.style.transform=`translate(-50%,${p*430}px) rotate(${p*540}deg)`;if(p>=1)langiJudge('miss');raf=requestAnimationFrame(langiLoop)}
  function langiTap(e){if(e?.target?.closest('button'))return;const y=session.langiY||0;if(y>.72)langiJudge('perfect');else if(y>.54)langiJudge('good');else{const out=document.querySelector('#langiFeedback');if(out){out.textContent='Әлі ерте';out.className='early'}}}
  function langiJudge(kind){if(session.lock)return;session.lock=true;session.attempts++;const ok=kind!=='miss';if(kind==='perfect'){session.score+=150;session.combo++}else if(kind==='good'){session.score+=90;session.combo++}else session.combo=0;session.bestCombo=Math.max(session.bestCombo,session.combo);session.correct+=ok?1:0;session.round=session.attempts;const out=document.querySelector('#langiFeedback');if(out){out.textContent=kind==='perfect'?'Perfect':kind==='good'?'Good':'Тағы байқап көр';out.className=kind};const combo=document.querySelector('#langiCombo');if(combo)combo.textContent=`x${session.combo>=10?2:session.combo>=5?1.5:session.combo>=3?1.2:1}`;if(ok&&session.combo%2===0){const facts=factsFor(session.work),fact=facts[(session.combo/2-1)%Math.max(1,facts.length)];if(fact)document.querySelector('#langiFact').textContent=fact}say(kind==='perfect'?'Керемет!':kind==='good'?'Жарайсың!':'Тағы бір рет ойланып көр.');later(()=>{if(session.attempts>=10)finish();else{session.langiStart=performance.now();session.lock=false}},reduceMotion()?80:430)}
  function factsFor(work){const works=work?[work]:richWorks(),facts=[];works.forEach(w=>{(w.content?.characters||[]).slice(0,3).forEach(c=>facts.push(`${c.name} — ${c.role||c.description}`));if(w.content?.mainIdea)facts.push(`${w.title}: ${w.content.mainIdea}`)});return facts}
  function renderRace(){if(session.round>=session.questions.length||session.player>=100||session.opponent>=100)return finish();const q=session.questions[session.round];session.questionAt=performance.now();document.querySelector('#ngShell').innerHTML=`${header()}<div class="ng-scene ng-kokpar-scene"><div class="ng-race-world"><i class="ng-race-sky"></i><i class="ng-mountains"></i><i class="ng-hills"></i><i class="ng-grass"></i><i class="ng-finish"></i><div class="ng-race-track"><span class="ng-racing-rider player" style="--progress:${session.player}%"><i></i><b></b></span><span class="ng-racing-rider rival" style="--progress:${session.opponent}%"><i></i><b></b></span></div><div class="ng-race-progress"><span style="width:${session.player}%"></span><b style="left:${session.player}%"></b></div></div>${qCard(q,'NationalGames.raceAnswer')}</div>`}
  function raceAnswer(index){const q=session.questions[session.round],ok=index===q.answer,elapsed=performance.now()-session.questionAt;session.correct+=ok?1:0;if(ok){const boost=elapsed<4500?25:17;session.player=Math.min(100,session.player+boost);session.score+=Math.max(70,Math.round(180-elapsed/50));session.combo++}else{session.opponent=Math.min(100,session.opponent+23);session.combo=0}session.opponent=Math.min(100,session.opponent+7);session.bestCombo=Math.max(session.bestCombo,session.combo);document.querySelector('.ng-race-world')?.classList.add(ok?'boost':'rival-boost');say(ok?'Алға! Керемет жауап!':'Қарсылас алға шықты — келесі сұрақ сенікі.');session.round++;later(renderRace,reduceMotion()?80:720)}
  function renderArkan(){if(session.round>=session.questions.length||Math.abs(session.position)>=55)return finish();const q=session.questions[session.round];document.querySelector('#ngShell').innerHTML=`${header()}<div class="ng-scene ng-arkan-scene"><div class="ng-tug-world ${session.position>0?'winning':session.position<0?'losing':''}" style="--pull:${session.position}"><i class="ng-tug-bg"></i><div class="ng-tug-team left"><span></span><span></span><span></span></div><div class="ng-real-rope"><i></i><b></b></div><div class="ng-tug-team right"><span></span><span></span><span></span></div><div class="ng-win-zone"><i></i></div></div>${qCard(q,'NationalGames.arkanAnswer')}</div>`}
  function arkanAnswer(index){const q=session.questions[session.round],ok=index===q.answer;session.correct+=ok?1:0;if(ok){session.combo++;session.position=Math.min(60,session.position+14+(session.combo>=3?7:0));session.score+=100+session.combo*15}else{session.combo=0;session.position=Math.max(-60,session.position-17)}session.bestCombo=Math.max(session.bestCombo,session.combo);document.querySelector('.ng-tug-world')?.classList.add(ok?'yank-left':'yank-right');say(ok?'Тамаша талдау! Арқан бізге қарай жылжыды.':'Тағы бір рет ойланып көр. Арқан қарсы жаққа кетті.');session.round++;later(renderArkan,reduceMotion()?80:650)}
  function finish(){cleanup();session.stage='result';const total=session.gameId==='langi'?10:Math.max(1,session.questions.length),accuracy=Math.round(session.correct/total*100),medal=accuracy>=85?'Алтын':accuracy>=60?'Күміс':'Қола',key=`${session.workId}:${session.gameId}`,p=readProgress(),old=p[key]||{};p[key]={plays:(old.plays||0)+1,bestScore:Math.max(old.bestScore||0,session.score),bestCombo:Math.max(old.bestCombo||0,session.bestCombo),medal:rank(medal)>rank(old.medal)?medal:(old.medal||medal),lastPlayed:new Date().toISOString(),completed:true};writeProgress(p);say('Тамаша! Бұл шығарманы жақсы меңгеріп келесің.');const next=GAME_IDS[(GAME_IDS.indexOf(session.gameId)+1)%GAME_IDS.length];document.querySelector('#ngShell').innerHTML=`<article class="ng-result ng-theme-${session.gameId}"><div class="ng-confetti"><i></i><i></i><i></i><i></i><i></i></div><div class="ng-award ${medal.toLowerCase()}"><span></span><b>${accuracy}%</b></div><span class="ng-kicker">Нәтиже · ${esc(workTitle())}</span><h1>${medal} жүлде</h1><p>${accuracy>=85?'Өте дәл әрі сенімді ойын!':accuracy>=60?'Жақсы нәтиже — тағы бір ойында шыңдай түс.':'Жақсы бастама. Шығарма деректерін қарап, қайта байқап көр.'}</p><div class="ng-result-grid"><span><b>${session.score}</b> ұпай</span><span><b>${accuracy}%</b> дәлдік</span><span><b>${session.bestCombo}</b> үздік серия</span><span><b>${session.correct}/${total}</b> дұрыс</span></div><div class="ng-result-actions"><button class="ng-start-btn" onclick="NationalGames.restart()">Қайта ойнау</button><button class="secondary" onclick="NationalGames.launch('${session.workId}','${next}')">Келесі ойын</button><button class="secondary" onclick="NationalGames.exit()">Ойындарға оралу</button>${session.work?`<button class="secondary" onclick="openWork('${session.work.id}')">Шығармаға оралу</button>`:''}</div><div class="ng-result-shyrak"><img src="assets/shyrak/shyrak-talking.png" alt="Шырақ"><span>Тамаша! Білімің артып келеді.</span></div></article>`;window.scrollTo(0,0)}
  function rank(m){return {'Қола':1,'Күміс':2,'Алтын':3}[m]||0}
  function keyHandler(e){if(session?.gameId==='langi'&&e.code==='Space'){e.preventDefault();langiTap()}}
  function restart(){const {workId,gameId,difficulty}=session;renderGame(workId,gameId);difficulty&&NationalGames.difficulty(difficulty);NationalGames.start()}
  function exit(){cleanup();location.hash=session?.workId&&session.workId!=='mix'?`games/${session.workId}`:'games'}
  function selectWork(id){renderHub(id)}
  function launch(work,id){location.hash=`games/${work}/${id}`}
  function openStoryBuilder(id){const work=byId(id)||byId('kokserak'),game=(work?.games||[]).find(g=>g.type==='order')||(byId('kokserak')?.games||[]).find(g=>g.type==='order');if(game)location.hash=`games/${work?.games?.includes(game)?work.id:'kokserak'}/${game.id}`}
  function openStoryRewrite(id){const work=byId(id)||byId('kokserak'),target=typeof window.safeWork==='function'&&window.safeWork(work.id)?work.id:'kokserak';window.currentWorkId=target;cleanup();root().innerHTML=`<section class="ng-game"><button class="back" onclick="NationalGames.renderHub('${target}')">← Ойындар орталығына</button><header class="ng-work-head"><div><span class="ng-kicker">Балама сюжет</span><h1>Сюжетті <em>өзгерту</em></h1><p>Түпнұсқа оқиға сақталады. Сен шешімдер арқылы ықтимал балама тармақтарды зерттейсің.</p></div></header><div id="workOutput"></div></section>`;if(typeof window.startAlternativeStory==='function')window.startAlternativeStory(target);syncNav();window.scrollTo(0,0)}
  function renameMapLabels(){document.querySelectorAll('[data-go="map"]').forEach(el=>{if(el.textContent.includes('Әдеби Қазақстан'))el.textContent=el.textContent.replace('Әдеби Қазақстан','Әдеби саяхат')});if(location.hash==='#map')document.querySelectorAll('.lk-intro h1').forEach(h=>{if(h.textContent!=='Әдеби саяхат')h.textContent='Әдеби саяхат'})}
  window.addEventListener('hashchange',cleanup);
  window.addEventListener('hashchange',()=>setTimeout(renameMapLabels,120));new MutationObserver(renameMapLabels).observe(document.querySelector('#app'),{childList:true,subtree:true});setTimeout(renameMapLabels,160);
  window.NationalGames={has:id=>GAME_IDS.includes(id),renderHub,renderWorkHub,renderGame,selectWork,launch,filter,openStoryBuilder,openStoryRewrite,difficulty,start,restart,exit,asykAnswer,raceAnswer,arkanAnswer,generateGameQuestions};
})();
