// Канондық дерек бөлігі: Object.freeze ойын немесе AI арқылы өзгертілмейді.
const CANONICAL_WORKS=Object.freeze({
  kokserak:Object.freeze({
    source:'kitap.kz және Қарағанды облысының ОӘОӘК оқу материалы',
    description:'«Көксерек» — Мұхтар Әуезовтің прозалық шығармасы; дереккөздерде жанры әңгіме және повесть деп әртүрлі көрсетіледі.',
    characters:Object.freeze([
      {id:'kurmash',name:'Құрмаш',role:'Бала кейіпкер',text:'Мәтін мазмұнында Құрмаш бөлтірікті асырап, оған Көксерек деп ат қояды.',visual:'👦'},
      {id:'kokserak',name:'Көксерек',role:'Қасқыр',text:'Шығармадағы қасқыр образы; Көксерек табиғи болмысын жоғалтпайды.',visual:'🐺'},
      {id:'aqqasqa',name:'Аққасқа',role:'Қасеннің иті',text:'Қасқыр алатын ит; финалда Көксерекпен айқасады.',visual:'◇'}
    ]),
    events:Object.freeze([
      {id:'e1',title:'Басталуы',text:'Бөлтіріктердің ішінен ең кішісі қолға түседі.',canonical:true},
      {id:'e2',title:'Дамуы',text:'Құрмаш бөлтірікті асырап, Көксерек деп ат қояды.',canonical:true},
      {id:'e3',title:'Шиеленісу',text:'Көксерек қасқырларға қосылып, малға шабады.',canonical:true},
      {id:'e4',title:'Шарықтау шегі',text:'Көксерек Құрмашқа шабады.',canonical:true},
      {id:'e5',title:'Шешімі',text:'Қасеннің Аққасқа иті Көксерекпен ақтық айқасқа түседі.',canonical:true}
    ]),
    relationship:'Құрмаш → асырап алған → Көксерек',
    decisions:Object.freeze([
      {id:'d1',context:'Құрмаш бөлтірікті асырай бастайды.',choices:[
        {id:'care',label:'Құрмаш оның табиғи болмысын түсінуге тырысады.',next:'Бұл — балама ой жүгірту: Құрмаш жануардың табиғи ортасына қатысты жауапкершілік жайлы ересектермен сөйлесуге ұмтылады.'},
        {id:'keep',label:'Құрмаш оны өзіне толық бағындыруға тырысады.',next:'Бұл — балама ой жүгірту: Көксеректің табиғи болмысын өзгертуге талпыныс шиеленісті азайтпайды.'}
      ]},
      {id:'d2',context:'Көксерек ауылдан алыстап, қасқырларға қосылады.',choices:[
        {id:'warn',label:'Ауыл адамдары қауіпсіздік пен малды қорғау жолын бірге талқылайды.',next:'Балама тармақ: қауым алдын ала әрекет етуге келіседі; бұл түпнұсқа оқиғаның орнына жүрмейді.'},
        {id:'chase',label:'Ауыл адамдары Көксеректі дереу қууға шешім қабылдайды.',next:'Балама тармақ: асығыс шешім қорқыныш пен қақтығысты күшейтуі мүмкін.'}
      ]}
    ])
  })
});
function safeWork(id){return CANONICAL_WORKS[id]||null}
window.openWork=function(id){let w=works.find(x=>x.id===id),c=safeWork(id);location.hash='work/'+id;app.innerHTML=`<section class="detail-hero"><button class="back" data-go="map">← Әдеби картаға оралу</button><div class="eyebrow" style="margin-top:28px">${w.genre} · ${w.period}</div><h1>${w.title}</h1><div class="detail-meta">Автор: ${w.author}</div></section><section class="detail-grid"><div><article class="work-card" style="min-height:0"><span class="story-status">${c?'ТЕКСЕРІЛГЕН ДЕРЕК БЕТІ':'ДЕРЕКТІ НАҚТЫЛАУ ҚАЖЕТ'}</span><h3>Шығарма туралы</h3><p class="muted">${c?c.description:'Бұл шығармаға арналған толық әдеби дерекқор тексерілу үстінде. Тексерілмеген кейіпкер, оқиға және дәйексөз көрсетілмейді.'}</p>${c?`<p class="muted">Дереккөз: ${c.source}</p>`:''}</article><div class="work-sections"><button onclick="workSection('${id}','characters')">👥 Кейіпкерлер</button><button onclick="workSection('${id}','plot')">🧭 Сюжет</button><button onclick="workSection('${id}','themes')">🎯 Тақырыптар</button><button onclick="workSection('${id}','ideas')">💡 Негізгі идея</button><button onclick="workSection('${id}','relations')">🔗 Байланыстар</button><button onclick="workSection('${id}','vocabulary')">📚 Сөздік</button><button onclick="games()">🎮 Ойындар</button><button onclick="launchGame('quiz')">🧠 Тест</button>${c?`<button onclick="startAlternativeStory('${id}')">🎭 Сюжетті өзгерту</button>`:''}</div><div id="workOutput" class="work-output"></div></div><aside class="work-card detail-side"><span class="tag">Прогресс</span><h3>Зерттеу жолы</h3><div class="progress-row"><span>Меңгеру</span><b>${completed?35:0}%</b></div><div class="track"><div class="fill" style="width:${completed?35:0}%"></div></div><p class="muted">Бөлімдерді зерттеп, тест арқылы біліміңізді бекітіңіз.</p><button class="primary" onclick="completeWork()">Зерттелді деп белгілеу</button></aside></section>`;window.scrollTo(0,0)}
window.workSection=function(id,type){let c=safeWork(id),out=document.querySelector('#workOutput');if(!c){out.innerHTML='<div class="notice">Ақпаратты нақтылау қажет. Тексерілген дерекқор толықтырылған соң бөлім ашылады.</div>';return}if(type==='characters')out.innerHTML=`<section class="section"><h2>Көксерек — кейіпкерлер</h2><div class="cards">${c.characters.map(x=>`<article class="work-card"><div class="character-visual" aria-label="Көркем визуализация">${x.visual}</div><span class="tag">Көркем визуализация</span><h3>${x.name}</h3><b>${x.role}</b><p class="muted">${x.text}</p><button class="small-btn" onclick="characterDetail('${id}','${x.id}')">Толығырақ →</button></article>`).join('')}</div></section>`;else if(type==='plot')out.innerHTML=`<section class="section"><h2>Сюжет</h2><div class="canonical-note">⚠️ Бұл бөлімде шығарманың шешімі туралы спойлерлер бар. <button class="link" onclick="revealPlot('${id}')">Сюжетті ашу</button></div></section>`;else if(type==='relations')out.innerHTML=`<section class="section"><h2>Кейіпкерлер байланысы</h2><button class="relationship" onclick="toast('Бұл байланыс Құрмаштың Көксеректі асырауына негізделген.')">${c.relationship} →</button></section>`;else if(type==='themes')out.innerHTML='<div class="notice">Тақырыптарды түсіндіруде тек тексерілген дерек пайдаланылуы тиіс. Қосымша талдау дерекқор толықтырылғаннан кейін беріледі.</div>';else if(type==='ideas')out.innerHTML='<div class="notice">Әдеби интерпретация фактіден бөлек беріледі. Бұл бөлімге дереккөзбен расталған талдау қажет.</div>';else out.innerHTML='<div class="notice">Сөздік бөлімі тек мәтіндік дереккөздермен тексерілгеннен кейін толтырылады.</div>'}
window.revealPlot=function(id){let c=safeWork(id);document.querySelector('#workOutput').innerHTML=`<section class="section"><h2>Сюжет желісі</h2><div class="timeline">${c.events.map(e=>`<div><b>${e.title}</b><br>${e.text}<br><small class="story-status">📘 ТҮПНҰСҚА ОҚИҒА</small></div>`).join('')}</div></section>`}
window.characterDetail=function(id,charId){let x=safeWork(id).characters.find(a=>a.id===charId);document.querySelector('#workOutput').innerHTML=`<section class="section"><button class="back" onclick="workSection('${id}','characters')">← Кейіпкерлерге оралу</button><article class="work-card"><div class="character-visual">${x.visual}</div><span class="tag">Көркем визуализация, фото емес</span><h2>${x.name}</h2><p><b>Рөлі:</b> ${x.role}</p><p class="muted"><b>Мәтіндегі дерек:</b> ${x.text}</p><p class="muted"><b>Әдеби түсіндіру:</b> Кейіпкер әрекетін талдау — оқырманның мәтінге сүйенген жеке пайымы; оны факт ретінде қабылдамау керек.</p></article></section>`}
window.startAlternativeStory=function(id){let c=safeWork(id),state={workId:id,step:0,choices:[]};renderAlternative(c,state)}
function renderAlternative(c,state){let box=document.querySelector('#workOutput');if(state.step>=c.decisions.length){let attempts=JSON.parse(localStorage.getItem('adebiet-alternative-attempts')||'[]');attempts.push({workId:state.workId,choices:state.choices,date:new Date().toISOString()});localStorage.setItem('adebiet-alternative-attempts',JSON.stringify(attempts));award(20);box.innerHTML=`<section class="game-panel"><div class="eyebrow">🎭 Балама аяқталу</div><h2>Ой жүгірту аяқталды</h2><p>Сіз ${state.choices.length} шешім қабылдадыңыз. Бұл тармақ — оқу рефлексиясы; ол «Көксерек» шығармасының түпнұсқа оқиғасын өзгертпейді.</p><div class="canonical-note"><b>Түпнұсқа шешімі:</b> ${c.events[c.events.length-1].text}</div><button class="primary" onclick="startAlternativeStory('${state.workId}')">Қайта ойнау</button><button class="secondary" data-go="profile">Профильге оралу</button></section>`;return}let d=c.decisions[state.step];box.innerHTML=`<section class="game-panel"><div class="story-status">📘 ТҮПНҰСҚА КОНТЕКСТ</div><p>${d.context}</p><div class="story-status">🔁 БАЛАМА ШЕШІМ</div><h2>Егер осы сәтте басқа шешім қабылданса не болар еді?</h2>${d.choices.map((ch,i)=>`<button class="story-choice" onclick="chooseAlternative(${i})">${String.fromCharCode(65+i)}. ${ch.label}</button>`).join('')}<div id="alternativeFeedback"></div></section>`;window.chooseAlternative=function(i){let ch=d.choices[i];state.choices.push({decisionId:d.id,choiceId:ch.id});document.querySelector('#alternativeFeedback').innerHTML=`<div class="result-line"><b>🔁 Балама оқиға</b><br>${ch.next}<br><button class="primary" style="margin-top:12px" onclick="nextAlternative()">Келесі шешім →</button></div>`;document.querySelectorAll('.story-choice').forEach(x=>x.disabled=true)};window.nextAlternative=function(){state.step++;renderAlternative(c,state)}}
function showAttemptCount(){if(location.hash!=='#profile')return;let attempts=JSON.parse(localStorage.getItem('adebiet-alternative-attempts')||'[]'),stats=document.querySelector('.stats');if(stats)stats.insertAdjacentHTML('beforeend',`<article class="stat-card"><span class="muted">Балама сюжет</span><strong>${attempts.length}</strong><span class="muted">талпыныс</span></article>`)}
window.addEventListener('hashchange',()=>setTimeout(showAttemptCount,0));
