(function(){
const E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),A=v=>Array.isArray(v)?v:[],covers={alpan:'assets/works/covers/alpan.png',balalyk:'assets/works/covers/balalyk.png',kan:'assets/works/covers/kan.png',qyzyl:'assets/works/covers/qyzyl.png'},nav=[['overview','Шолу'],['characters','Кейіпкерлер'],['plot','Сюжет'],['themes','Тақырыптар'],['relations','Байланыстар'],['vocabulary','Сөздік'],['games','Ойындар']];let work,io;
const key=()=>`adebiet-work-viewed:${work.id}`,seen=()=>{try{return new Set(JSON.parse(localStorage.getItem(key())||'[]'))}catch{return new Set()}},progress=s=>{let p=Math.round(s.size/nav.length*100);document.querySelectorAll('.wd-pct').forEach(x=>x.textContent=p+'%');document.querySelectorAll('.wd-fill').forEach(x=>x.style.width=p+'%')},mark=id=>{let s=seen();s.add(id);localStorage.setItem(key(),JSON.stringify([...s]));progress(s)},initials=n=>n.split(/\s+/).slice(0,2).map(x=>x[0]).join('');
const svg=(body,label)=>`<svg viewBox="0 0 80 80" role="img" aria-label="${E(label)}" fill="none" xmlns="http://www.w3.org/2000/svg">${body}</svg>`;
function avatarType(x){if(x.avatarType)return x.avatarType;const s=`${x.name} ${x.role} ${x.description}`.toLocaleLowerCase('kk-KZ');if(/қасқыр|ит|жануар|бөлтірік/.test(s))return'animal';if(/бала|ұл|қыз|жеткіншек/.test(s))return /қыз/.test(s)?'girl':'boy';if(/ана|әйел|жұбайы/.test(s))return'woman';if(/әке|шал|қария|би|ата/.test(s))return'elder';return'neutral'}
function avatar(x){if(x.avatar)return `<span class="wd-avatar image"><img src="${E(x.avatar)}" alt="${E(x.name)}"></span>`;const type=avatarType(x),animal=svg('<path d="M18 35 12 17l18 10M62 35l6-18-18 10" fill="#b99068"/><path d="M16 42c0-18 12-29 24-29s24 11 24 29-11 27-24 27S16 60 16 42Z" fill="#8d735e"/><path d="M25 43h5m20 0h5" stroke="#263b35" stroke-width="4" stroke-linecap="round"/><path d="m34 54 6 4 6-4" stroke="#263b35" stroke-width="3" stroke-linecap="round"/>',`${x.name}: жануар бейнесі`),person=svg(`<circle cx="40" cy="28" r="16" fill="#d6ad87"/><path d="M18 73c2-18 11-27 22-27s20 9 22 27" fill="${type==='woman'||type==='girl'?'#477b72':'#597386'}"/><path d="M24 29c1-15 9-21 16-21s15 6 16 21c-6-6-11-9-16-9s-10 3-16 9Z" fill="${type==='elder'?'#d8d1c3':'#493b32'}"/>${type==='elder'?'<path d="M31 37c4 7 14 7 18 0" stroke="#eee6d8" stroke-width="5" stroke-linecap="round"/>':''}<circle cx="34" cy="29" r="1.7" fill="#263b35"/><circle cx="46" cy="29" r="1.7" fill="#263b35"/>`,`${x.name}: әдеби кейіпкер бейнесі`);return `<span class="wd-avatar type-${type}">${type==='animal'?animal:person}</span>`}
function chars(c){let a=A(c.characters);return a.length?`<div class="wd-characters">${a.map(x=>`<article>${avatar(x)}<div><small>${E(x.role||'Кейіпкер')}</small><h3>${E(x.name)}</h3><p>${E(x.description)}</p>${x.action?`<details><summary>Толығырақ</summary><p>${E(x.action)}</p></details>`:''}</div></article>`).join('')}</div>`:empty('Тексерілген кейіпкерлер тізімі әзірленуде.')}
function plot(c){let a=A(c.plotEvents);return a.length?`<ol class="wd-timeline">${a.map((x,i)=>`<li><b>${i+1}</b><div><h3>${E(x.title||x.name||`Оқиға ${i+1}`)}</h3><p>${E(x.description||x.text||x.summary)}</p></div></li>`).join('')}</ol>`:`<article class="wd-summary"><small>Сюжет желісі</small><p>${E(c.plotSummary||'Тексерілген мазмұн әзірленуде.')}</p></article>`}
const empty=t=>`<div class="wd-empty">${t}</div>`,head=(n,k,t)=>`<header><span>${n}</span><div><small>${k}</small><h2>${t}</h2></div></header>`;
function render(w){work=w;let c=w.content||{},cover=covers[w.id],themes=A(c.themes),rels=A(c.relationships),voc=A(c.vocabulary),games=A(w.games);document.querySelector('#app').innerHTML=`<main class="wd-page tone-${E(w.tone||'cream')}"><section class="wd-hero"><div class="wd-copy"><button class="wd-back" data-go="library">← Шығармаларға оралу</button><small class="wd-kicker">${E(w.period)}</small><h1>${E(w.title)}</h1><h2>${E(w.author)}</h2><div class="wd-meta"><span>${E(w.genre)}</span>${w.verificationStatus==='VERIFIED'?'<span>✓ Тексерілген дерек</span>':''}</div><p>${E(w.intro||c.plotSummary)}</p><div class="actions"><button class="primary" onclick="WorkDetailPage.go('overview')">Зерттеуді бастау</button><button class="secondary" onclick="openWorkGames('${E(w.id)}')">Ойынға өту</button></div><div class="wd-progress"><span>Зерттеу барысы</span><b class="wd-pct">0%</b><i><em class="wd-fill"></em></i></div></div>${cover?`<figure><img src="${cover}" alt="${E(w.title)} постері"></figure>`:`<figure class="fallback"><div><small>ӘДЕБИ САЯХАТ</small><b>${E(initials(w.title))}</b><span>${E(w.period)}</span></div></figure>`}</section>
<section class="wd-quick">${[['characters','users','Кейіпкерлер'],['plot','book','Сюжет'],['themes','layers','Тақырыптар'],['main-idea','idea','Негізгі идея'],['relations','connections','Байланыстар'],['vocabulary','dictionary','Сөздік'],['games','gamepad','Ойындар'],['games','quiz','Тест'],['games','branch','Сюжетті квест']].map(x=>`<button onclick="WorkDetailPage.go('${x[0]}')"><i>${window.LiteraryIcons?.render(x[1])||''}</i><b>${x[2]}</b></button>`).join('')}</section><nav class="wd-nav">${nav.map(x=>`<button data-wd="${x[0]}" onclick="WorkDetailPage.go('${x[0]}')">${x[1]}</button>`).join('')}</nav><div class="wd-body">
<section id="overview" class="wd-section">${head('01','Шығарма әлемі','Шолу')}<div class="wd-overview"><article><h3>Қысқаша мазмұны</h3><p>${E(c.plotSummary||w.intro)}</p></article><aside><div><small>Оқиға орны мен уақыты</small><p>${E(c.setting||'Дерек нақтылануда')}</p></div><div><small>Негізгі тартыс</small><p>${E(c.conflict||'Дерек нақтылануда')}</p></div></aside></div></section>
<section id="characters" class="wd-section">${head('02','Тұлғалар','Кейіпкерлер')}${chars(c)}</section><section id="plot" class="wd-section">${head('03','Оқиға қозғалысы','Сюжет')}${plot(c)}</section>
<section id="themes" class="wd-section">${head('04','Мағына қабаттары','Тақырыптар')}${themes.length?`<div class="wd-themes">${themes.map((x,i)=>`<article><i>0${i+1}</i><h3>${E(x)}</h3></article>`).join('')}</div>`:empty('Тексерілген тақырыптар әзірленуде.')}<article id="main-idea" class="wd-idea"><small>Негізгі идея</small><p>${E(c.mainIdea||'Тексерілген негізгі идея әзірленуде.')}</p></article></section>
<section id="relations" class="wd-section">${head('05','Кейіпкерлер жүйесі','Байланыстар')}${rels.length?`<div class="wd-relations">${rels.map(x=>`<article><b>${E(x.from)}</b><span>${E(x.type)}</span><b>${E(x.to)}</b></article>`).join('')}</div>`:empty('Тексерілген байланыстар әзірленуде.')}</section>
<section id="vocabulary" class="wd-section">${head('06','Тіл мен контекст','Сөздік')}${voc.length?`<input class="wd-search" placeholder="Сөзді іздеу" oninput="WorkDetailPage.filter(this.value)"><div class="wd-vocab">${voc.map(x=>`<article data-term="${E((x.term+' '+x.definition).toLowerCase())}"><b>${E(x.term)}</b><p>${E(x.definition)}</p></article>`).join('')}</div>`:empty('Бұл шығармаға арналған тексерілген сөздік әзірленуде.')}</section>
<section id="games" class="wd-section">${head('07','Ойнап бекіту','Ойындар мен тапсырмалар')}<div class="wd-games">${games.length?games.map(g=>`<article><i>${window.LiteraryIcons?.render(g.icon||'gamepad')||''}</i><div><small>${E(g.difficulty||'Оқу ойыны')}</small><h3>${E(g.title)}</h3><p>${E(g.learningObjective)}</p><button onclick="openGame('${E(w.id)}','${E(g.id)}')">Ойынды бастау →</button></div></article>`).join(''):empty('Тексерілген ойындар кейінірек қосылады.')}</div><button class="secondary" onclick="openWorkGames('${E(w.id)}')">Барлық оқу ойындары</button></section><footer><h2>Шығарманы оқу жолына қосыңыз</h2><button class="primary" onclick="markWorkComplete('${E(w.id)}')">✓ Зерттелді деп белгілеу</button></footer></div></main>`;progress(seen());if(io)io.disconnect();io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){mark(e.target.id);document.querySelectorAll('[data-wd]').forEach(b=>b.classList.toggle('active',b.dataset.wd===e.target.id))}}),{rootMargin:'-25% 0px -65%'});document.querySelectorAll('.wd-section').forEach(x=>io.observe(x));scrollTo(0,0)}
window.WorkDetailPage={render,go:id=>{let x=document.getElementById(id);if(x){x.scrollIntoView({behavior:'smooth'});mark(id==='main-idea'?'themes':id)}},filter:q=>document.querySelectorAll('[data-term]').forEach(x=>x.hidden=!x.dataset.term.includes(q.toLowerCase()))};
})();
